# Evaluating Attribute Annotations

In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.set_option('display.max_rows', None)
pd.set_option("display.max_colwidth", None)

In [5]:
df_combined = pd.read_csv("../data/evaluation/annotation_with_complete_with_curation_and_llm.csv", encoding="utf-8-sig")

### Standardized Attributes

In [453]:
from sklearn.metrics import cohen_kappa_score
def eval_standardized(suff1, suff2, label, na=False):
    for attr in ["ReasonForCheck", "VehicleType", "SubstanceUsed", "LicenseStatus", "TypeOfRoad", "RefusedTesting", "Measuringmethods"]:
        if na:
            df_clean = df_combined.replace(np.nan,"n/a", inplace=False)
        else:
            df_clean = df_combined.replace("n/a", np.nan, inplace=False)
            df_clean = df_clean.dropna(subset=[f"{attr}.{suff1}", f"{attr}.{suff2}"])
        df_clean = df_clean.applymap(
        lambda x: (
            "; ".join(sorted(set(i.strip() for i in str(x).split(";") if i.strip())))
            if pd.notnull(x) else x
        )
    )
        print(f"Evaluating all {len(df_clean)} records for {attr}")
        print("\nAccuracy")
        accuracy = (df_clean[f"{attr}.{suff1}"] == df_clean[f"{attr}.{suff2}"]).sum()/len(df_clean)
        #print(f'Annot1 vs. Annot2: {(df2[f"{attr}.value.0"] == df2[f"{attr}.value.1"]).sum()/len(df2)}')
        print(f'{label} {accuracy}')
        
        print("\nCohen's Kappa")
        #kappa = cohen_kappa_score(df2[f"{attr}.value.0"], df2[f"{attr}.value.1"])
        #print(f'Annot1 vs. Annot2: {kappa}')
        kappa = cohen_kappa_score(df_clean[f"{attr}.{suff2}"], df_clean[f"{attr}.{suff1}"])
        print(f'{label} {kappa}\n\n')
        print(f'{attr} & {accuracy} & {kappa}')

In [492]:
from sklearn.metrics import cohen_kappa_score
def eval_all_standardized():
    for attr in ["ReasonForCheck", "VehicleType", "SubstanceUsed", "LicenseStatus", "TypeOfRoad", "RefusedTesting", "Measuringmethods"]:

        #df_clean = df_combined.replace(np.nan,"n/a", inplace=False)
        #df_clean = df_combined.replace("n/a", np.nan, inplace=False)
        #df_clean = df_clean.dropna(subset=[f"{attr}.value.curated", f"{attr}.llm"])
        df_clean = df_combined.replace(np.nan,"n/a", inplace=False).replace("None","n/a", inplace=False)
        df_clean = df_clean.applymap(
        lambda x: (
            "; ".join(sorted(set(i.strip() for i in str(x).split(";") if i.strip())))
            if pd.notnull(x) else x
        )
    )
        accuracy_llm = (df_clean[f"{attr}.value.curated"] == df_clean[f"{attr}.llm"]).sum()/len(df_clean)*100
        kappa_llm = cohen_kappa_score(df_clean[f"{attr}.llm"], df_clean[f"{attr}.value.curated"])*100
        accuracy_annot = (df_clean[f"{attr}.value.0"] == df_clean[f"{attr}.value.1"]).sum()/len(df_clean)*100
        kappa_annot = cohen_kappa_score(df_clean[f"{attr}.value.1"], df_clean[f"{attr}.value.0"])*100
        print(f'{attr}  & {accuracy_annot:.2f} & {kappa_annot:.2f} & {accuracy_llm:.2f} & {kappa_llm:.2f}')
eval_all_standardized()

ReasonForCheck  & 53.96 & 25.11 & 36.63 & 22.66
VehicleType  & 74.75 & 33.07 & 91.09 & 63.27
SubstanceUsed  & 66.34 & 34.54 & 72.28 & 36.06
LicenseStatus  & 93.07 & 58.44 & 92.08 & 61.45
TypeOfRoad  & 53.96 & 35.96 & 47.03 & 32.05
RefusedTesting  & 98.02 & 84.73 & 98.02 & 85.64
Measuringmethods  & 66.83 & 35.79 & 74.26 & 39.35

### Span Attributes

In [445]:
import re
from sklearn.metrics import cohen_kappa_score
def eval_span(suf1, suf2, label, na=False):
    for attr in ["TimeOfOffense", "DateOfOffense", "MeasuringTime", "AmountUsed"]:
        if na:
            df_clean = df_combined.replace(np.nan,"n/a", inplace=False)
        else:
            df_clean = df_combined.replace("n/a", np.nan, inplace=False)
            df_clean = df_clean.dropna(subset=[f"{attr}.{suf1}", f"{attr}.{suf2}"])
        df_clean = df_clean.applymap(
        lambda x: (
            "; ".join(sorted(set(i.strip() for i in str(x).split(";") if i.strip())))
            if pd.notnull(x) else x
        )
    )
        # Eval match between digit characters only
        df_clean = df_clean.applymap(
        lambda x: re.sub(r"\D", "", str(x)) if pd.notnull(x) else x
    )
        print(f"Evaluating all {len(df_clean)} records for {attr}")
        print("\nAccuracy")
        #print(f'Annot1 vs. Annot2: {(df2[f"{attr}.value.0"] == df2[f"{attr}.value.1"]).sum()/len(df2)}')
        print(f'{label} {(df_clean[f"{attr}.{suf1}"].apply(lambda x: str(x).split(";")[0].strip()) == df_clean[f"{attr}.{suf2}"]).sum()/len(df_clean)}\n\n')

In [486]:
from sklearn.metrics import cohen_kappa_score
def eval_all_span():
    for attr in ["TimeOfOffense", "DateOfOffense", "MeasuringTime", "AmountUsed"]:

        df_clean = df_combined.replace(np.nan,"n/a", inplace=False)
        #df_clean = df_combined.replace("n/a", np.nan, inplace=False)
        #df_clean = df_clean.dropna(subset=[f"{attr}.text.curated", f"{attr}.llm"])
        #df_clean = df_clean.replace(np.nan,"n/a", inplace=False).replace("None","n/a", inplace=False)
        df_clean = df_clean.applymap(
        lambda x: (
            "; ".join(sorted(set(i.strip() for i in str(x).split(";") if i.strip())))
            if pd.notnull(x) else x
        )
    )
        # Eval match between digit characters only
        df_clean = df_clean.applymap(
        lambda x: re.sub(r"\D", "", str(x)) if pd.notnull(x) else x
    )
        accuracy_llm = (df_clean[f"{attr}.text.curated"] == df_clean[f"{attr}.llm"]).sum()/len(df_clean)*100

        accuracy_annot = (df_clean[f"{attr}.text.0"] == df_clean[f"{attr}.text.1"]).sum()/len(df_clean)*100

        print(f'{attr} & {accuracy_annot:.2f} & n/a & {accuracy_llm:.2f} & n/a')
eval_all_span()

TimeOfOffense & 83.66 & n/a & 94.55 & n/a
DateOfOffense & 85.64 & n/a & 99.50 & n/a
MeasuringTime & 75.25 & n/a & 81.19 & n/a
AmountUsed & 76.73 & n/a & 90.10 & n/a

## Validation

In [184]:
allowed = {"SubstanceUsed":["alcohol", "cannabis", "methamphetamine", "amphetamine", "cocaine", "mdma", "hashish", "morphine", "other", "n/a"],
          "ReasonForCheck": ["traffic_accident", "speeding", "traffic_violation", "suspected_intoxication", "traffic_check", "other", "n/a"],
          "VehicleType": ["car", "van", "truck", "bus", "motorcycle", "other", "n/a"],
          "LicenseStatus": ["banned", "none", "valid", "n/a"],
          "Measuringmethods": ["blood", "breath", "urine", "n/a"],
          "RefusedTesting": ["yes", "no"]

}

In [217]:
for attr in ["ReasonForCheck", "VehicleType", "LicenseStatus", "SubstanceUsed", "Measuringmethods", "RefusedTesting"]:
    val = sum(df_combined[f"{attr}.llm"].apply(
        lambda x: any(tag.strip() in allowed[attr] for tag in x.split(";"))
    ))
    print(f"{val/len(df_combined)*100} % validated for attribute {attr}")

1.0 % validated for attribute ReasonForCheck
1.0 % validated for attribute VehicleType
1.0 % validated for attribute LicenseStatus
0.8960396039603961 % validated for attribute SubstanceUsed
1.0 % validated for attribute Measuringmethods
1.0 % validated for attribute RefusedTesting

## Discrepancies

In [444]:
cols = [f"{attr}.value.0", f"{attr}.value.1", f"{attr}.llm"]
subset = df[cols + ["text"]]  # keep those 3 + the text column

# Keep only rows where not all values are the same
mask = subset[cols].nunique(axis=1) > 1
discrepancies = subset[mask]

display(discrepancies)

,VehicleType.value.0,VehicleType.value.1,VehicleType.llm,text
0,car,n/a,car,"dňa 07.11.2022 v čase o 06:55 hod. v meste V. na ulici S.. V.. Š. po ceste II. triedy č. 532 viedol ako vodič osobné motorové vozidlo značky Škoda Octavia Combi, evidenčného čísla RA595AZ, po tom, čo požil alkoholické nápoje, pričom pred areálom spoločnosti MOSS.SK, s. r. o. Revúca bol zastavený a kontrolovaný hliadkou Okresného riaditeľstva Policajného zboru SR, Okresného dopravného inšpektorátu Revúca, kde vykonanou dychovou skúškou na zistenie prítomnosti alkoholu analyzátorom dychu typu „Dräger Alcotest 7510 classic“ výrobného čísla ARMF-0489 mu dňa 07.11.2022 o 06:56 hod. bolo nameraných 0,74 mg etanolu na liter vydychovaného vzduchu, čo je 1,54 promile,"
7,n/a,car,car,"dňa XX. XX. XXXX v čase o XX.XX hod. viedol ako vodič osobné motorové vozidlo zn. BMW ev. č. T. po ceste I. triedy č. XX po ul. Š. v meste C., kde bol predpísaným spôsobom zastavovaný, pričom na tieto výzvy vôbec nereagoval, naopak zrýchlil a v jazde pokračoval ďalej až na ul. R., kde pred rodinným domom č. 271/2 vozidlo zastavil, vyskočil z vozidla a začal utekať preč, pričom bol následne hliadkou OO PZ v Tornali spacifikovaný a pri služobnom zákroku bol použitý varovný výstrel do vzduchu, donucovacie prostriedky hmaty, chmaty a služobné putá a pri kontrole sa na výzvu policajta dňa XX. XX. XXXX v čase o XX.XX hod. odmietol podrobiť dychovej skúške na zistenie, či nie je ovplyvnený návykovou látkou analyzátorom dychu AlcoQuant 6020 plus výr. č. A409739 a taktiež sa odmietol podrobiť lekárskemu vyšetreniu odberom a vyšetrením krvi alebo iného biologického materiálu, hoci by to pri vyšetrení nebolo spojené s nebezpečenstvom pre jeho zdravie, následne pred umiestnením do cely policajného zaistenia zriadenej na OO PZ v Revúcej bol dňa XX. XX. XXXX v čase o XX.XX hod. podrobený dyhovej skúške analyzátorom dychu AlcoQuant 6020 plus výr. č. A408962, ktorým mu bola nameraná hodnota 0,71 miligramu etanolu na liter vydychovaného vzduchu, čo je pozitívny výsledok,"
9,n/a,car,car,", ž e - dňa 17.12.2021 v čase približne o 19:00 hod. viedol ako vodič motorové vozidlo zn. C. S., ev. č. S. po ceste II/519 v smere od obce Slovenské Pravno do obce Rudno, kde pri kilometrovníku 13,0 zišiel s vozidlom mimo cestu vľavo, pričom z miesta odišiel a následne, keď sa k motorovému vozidlu zn. C. S., ev. č. S. vrátil, bol po riadnom poučení vyzvaný, aby sa podrobil dychovej skúške na zistenie požitia alkoholu do elektronického prístroja Alcotest 7510, výrobné číslo ARMF-0427, kde metódou merania etanolu vo vydychovanom vzduchu mu bola dňa 17.12.2021 v čase o 20:47 hod. nameraná hodnota 1,07 mg/l alkoholu vo vydychovanom vzduchu, čo v prepočte predstavuje 2,23 ‰, opakovanou dychovou skúškou dňa 17.12.2021 v čase o 21:03 hod. nameraná hodnota 1,10 mg/1 alkoholu vo vydychovanom vzduchu, čo v prepočte predstavuje 2,29 ‰ a ďalšou opakovanou dychovou skúškou dňa 17.12.2021 v čase o 21:19 hod. nameraná hodnota 1,01 mg/l alkoholu vo vydychovanom vzduchu, čo v prepočte predstavuje 2,10 ‰, pričom na základe odborného vyjadrenia znalca prof. MUDr. Ľ. X., PhD. zo dňa 30.12.2021 vyplýva, že koncentrácia alkoholu v krvi obvineného bola dňa 17.12.2021 v čase o 19:00 hod. minimálne vo výške 1,33 až 1,48 ‰,"
12,n/a,car,car,", ž e dňa 06. novembra 2022 v čase okolo 22:40 hod. na miestnej komunikácii v obci Kluknava z parkoviska pod kaštieľom na parkovisko pred predajňou CBA a následne po parkovisku pred predajňou CBA, po predchádzajúcom požití alkoholu, ktorým sa priviedol do stavu vylučujúceho spôsobilosť bezpečne viesť motorové vozidlá, viedol osobné motorové vozidlo továrenskej značky Volkswagen Golf, evidenčného čísla J. XXX F., pričom dychovou skúškou elektronickým prístrojom AlcoQuant 6020 plus mu bola nameraná hodnota 1,27 mg/l alkoholu v dychu,"
13,n/a,car,car,"dňa XX.XX.XXXX v čase približne o XX:XX hod. v obci G. Y. smerom na obec S. riadil osobné motorové vozidlo zn. S. D., ev. č. BN XXX CH, kde bol pred domom č. XXX zastavený a kontrolovaný hliadkou OR PZ O. nad O., v rámci kontroly sa podrobil dychovej skúške, ktorú vykonal s negatívnym výsledkom, nakoľko však javil známky požitia omamných a psychotropných látok bol následne uvedenou hliadkou vyzvaný na podrobenie sa lekárskemu vyšetreniu odberom krvi a iného biologického materiálu, ktorému sa dňa XX.XX.XXXX v čase o XX:XX hod. dobrovoľne podrobil a z výsledkov laboratórnych vyšetrení toxikologicko-chemickej analýzy vykonanou v W. a patologicko anatomickom pracovisku O. O. bola v jemu odobratej vzorke krvi zistená prítomnosti metamfetamínu v koncentrácii XXXX ng/ml a amfetamínu v koncentrácii XXX ng/ml, pričom v zmysle zákona NR SR č. XXX/XXXX Z. z. o omamných látkach, psychotropných látkach a prípravkoch v znení neskorších predpisov sú metamfetamín a amfetamín zaradené do II. skupiny psychotropných látok, a toto u neho vyvolalo stav ťažkého stupňa opitosti s približnou koncentráciou alkoholu v krvi okolo X,X promile a viac,"
18,car,n/a,car,"že dňa 09.11.2022 v čase o 22.50 hod. po predchádzajúcom požití alkoholu viedol osobné motorové vozidlo zn. Škoda Felicia e. č. W.-XXX P. po ulici Rudnej v obci Nižnoslanská Baňa, okres Rožňava, kde bol z dôvodu, že nepoužíval znamenie o zmene smeru jazdy hliadkou OO PZ Dobšiná predpísaným spôsobom zastavený, pričom vykonanou dychovou skúškou bolo v čase o 22.35 hod. prístrojom AlcoQuant 6020 plus zistené, že v čase vedenia motorového vozidla mal v jednom litri ním vydychovaného vzduchu najmenej 0,66 mg/l alkoholu"
19,car,n/a,car,"dňa 23.10.2022 v čase o 15.20 hod. v stave vylučujúcom spôsobilosť viedol osobné motorové vozidlo značky Škoda Octavia Combi, červenej farby s EVČ: V po ceste III/2306 v obci Brezovica v smere od mesta Trstená k obecnému úradu, kde bol službukonajúcou hliadkou Obvodného oddelenia PZ Trstená predpísaným spôsobom pri budove s popisným číslom 43/68 zastavený a kontrolovaný, pričom počas kontroly sa podrobil dychovej skúške do elektronického merača zn. AlcoQuant 6020 plus, sériové číslo: A410037, ktorý dňa 23.10.2022 v čase o 15.25 hod. nameral hodnotu 0,55 mg/l alkoholu v dychu a dňa 23.10.2022 v čase 15:41 hod. nameral hodnotu 0,57 mg/l alkoholu v dychu,"
21,car,n/a,car,"dňa 15. 11. 2022 v čase o 18.26 hodine na pozemnej komunikácií v obci Zlaté Klasy, na Seneckej ceste pred rodinným domom so súpisným číslom 1067, okres Dunajská Streda, po predchádzajúcom požití presne nezisteného množstva alkoholických nápojov ako vodič viedol osobné motorové vozidlo značky Renault Megane s evidenčným číslom W.-XXXHY šedej farby, pričom bol riadne zastavený hliadkou Obvodného oddelenia Policajného zboru Šamorín a nakoľko počas kontroly javil známky požitia alkoholických nápojov, po zákonnom poučení bol podrobený dychovej skúške elektronickým meračom typu Alcotest 7510 elassie, číslo prístroja ARMF-0550, ktorým mu v čase 0 18.26 hod. dňa 15.11. 2022 bola nameraná hodnota 0,79 mg/l alkoholu v dychu (v prepočte 1 ,65 promile),"
23,car,motorcycle,car,"dňa XX.XX.XXXX v čase o XX.XX h viedol po ceste P./XXXX medzi mestom R. a obcou N. E. v okrese F. osobné motorové vozidlo zn. S. XXX, EČ: F po predchádzajúcom požití alkoholických nápojov, pričom bol zastavený a kontrolovaný hliadkou Obvodného oddelenia PZ R., ktorá u neho pri vykonanej dychovej skúške v uvedený deň v čase o XX.XX h namerala hodnotu 0,88 miligramu etanolu na liter vydýchnutého vzduchu a v čase o XX.XX h hodnotu 0,85 miligramu etanolu na liter vydýchnutého vzduchu,"
24,n/a,other,other,"dňa 14.11.2022 v čase o 9:32 h viedol v stave vylučujúcom spôsobilosť, ktorý si privodil vplyvom alkoholu (0,73 miligramu etanolu na liter vydýchnutého vzduchu) po ceste W. v smere z obce T. do mesta J. G. J., motorové vozidlo traktor zn. X. ev. č. C. V. XXX,"
25,n/a,car,car,"dňa 16.10.2022 v čase o 19.35 h v Novom Meste nad Váhom po miestnej komunikácii F. I. smerom na cestu Z. viedla po požití alkoholu, s výsledkom merania 0,77 miligramu etanolu na liter vydýchnutého vzduchu, osobné motorové vozidlo Š. K., ev. č.Q.,"
27,n/a,car,car,"dňa XX.XX.XXXX v čase okolo XX:XX hod. ako vodič bez príslušného vodičského oprávnenia viedol osobné motorové vozidlo zn. Q. Q. J..Č..: H. po miestnej komunikácii v obci I., okr. H. a to od domu č. XXX k domu č. XXX, kde bol zastavený a kontrolovaný hliadkou Obvodného oddelenia PZ Y. a následne po stotožnení v čase o XX:XX hod. uvedeného dňa bol podrobený dychovej skúške el. meračom Z. XXXX C. Č.. Z. XXXXXX (číslo merania XXXX), ktorým mu bola nameraná koncentrácia alkoholu 0,61 mg etanolu na liter vydychovaného vzduchu a opakovanou dychovou skúškou vykonanou v čase o XX.XX hod. uvedeného dňa totožným meračom (číslo merania XXXX), mu bola nameraná koncentrácia alkoholu 0,59 mg etanolu na liter vydychovaného vzduchu, pričom viedol motorové vozidlo aj napriek tomu, že rozsudkom Okresného súdu Bardejov sp. zn. XT/XX/XXXX zo dňa 25.11.2020 v spojitosti s rozsudkom Krajského súdu Prešov sp.zn. XTo/X/XXXX zo dňa 19.05.2021 bol uznaný vinným aj zo spáchania prečinu ohrozenia pod vplyvom návykovej látky podľa § 289 ods. 3 písm. a/, b/ Tr. zákona a bol mu okrem iného uložený aj trest zákazu činnosti viesť motorové vozidlá všetkého druhu v trvaní X (Š.) M., a rozsudkom Okresného súdu Trebišov sp. zn. XT XXX/XXXX v spojení s uznesením Krajského súdu Košice sp. zn. XTo/XX/XXXX zo dňa 24.06.2020 bol uznaný vinným zo spáchania prečinu ohrozenia pod vplyvom návykovej látky podľa § 289 ods. 1 Tr. zákona a rozsudkom Okresného súdu Bardejov, sp. zn. XT/XX/XXXX zo dňa 10.11.2021 právoplatným dňom 12.11.2021 mu bol okrem iného uložený aj súhrnný trest zákazu činnosti viesť motorové vozidlá všetkého druhu v trvaní X (U.) M. Z. X (Š.) I., pričom v čase vedenia vozidla uvedené doby zákazu činnosti viesť motorové vozidlá všetkého druhu ešte neuplynuli"
29,car,n/a,car,"dňa XX.XX.XXXX v čase okolo XX.XX hod. bez príslušného vodičského oprávnenia a v stave vylučujúcom spôsobilosť viedol osobné motorové vozidlo zn. F. G., EČ: C. po ceste I/77 cez obec D. smerom na mesto Bardejov, kde pri potravinách B. H. I. J. K. E. D., E.. C. z dôvodu nerozsvietenia stretávacích svetlometov na vozidle a nekoordinovanej jazdy bol zastavený a kontrolovaný hliadkou PMJ KR PZ Prešov, vysunuté pracovisko C. a po jeho stotožnení bol dňa XX.XX.XXXX v čase o XX.XX hod. podrobený dychovej skúške, ktorou bolo zistené, že obvinený viedol vozidlo po predchádzajúcom požití alkoholických nápojov, ktoré zvýšili hladinu etanolu v jeho krvi najmenej na 0,95 mg/l zistenú z vydychovaného vzduchu, čím obvinený porušil ustanovenie § 4 ods. 2 písm. a/, d/, § 32 ods. 1 v nadväznosti na ustanovenie § 137 ods. 1, ods. 2 písm. a/, q/ zákona č. 8/2009 Z.z. o cestnej premávke a o zmene a doplnení niektorých zákonov v znení neskorších predpisov"
30,car,n/a,car,"v Košiciach po ul. Milosrdenstva 36 dňa 25.10.2022 v čase o 07.25 hod. v stave vylučujúcom spôsobilosť viedla osobné motorové vozidlo zn. N. O., EVČ: E kde bola zastavená a kontrolovaná hliadkou OO PZ Košice-Juh, pričom bola podrobená dychovej skúške na určenie objemového percenta alkoholu v dychu prístrojom Alcoquant 6020 plus ev.č. A 409970, pri ktorej jej bola nameraná pozitívna hodnota alkoholu v dychu 0,73 mg/l;"
32,n/a,n/a,car,"z prečinu ohrozenia pod vplyvom návykovej látky podľa § 289 ods. 1 Trestného zákona, že dňa 05..11.2022 o 22.54 hod., v Prešove, potom čo požil alkoholické nápoje, viedol po ulici Pod táborom smerom na sídlisko Sekčov osobné motorové vozidlo zn. E. XXX EČ E. XXX H., pričom bol zastavený a kontrolovaný hliadkou OO PZ Prešov juh, kde pri dychovej skúške na alkohol v čase o 22.58 hod. mu bola nameraná hodnota 1,03 mg/l alkoholu v dychu, pričom obvinený svojim konaním porušil ust. § 4 ods. 2 písm. d/ Zák. č. 8/2009 o cestnej premávke,"
42,car,n/a,car,", že dňa 22.06.2022 v čase o 23.40 hod. v Bratislave na Vysokej ulici smerom na Staromestskú ulicu viedol osobné motorové vozidlo zn. Mercedes- Benz C 300d, čiernej farby, EČV: (I.) G.-XXXJF, pričom bol hliadkou Pohotovostnej motorizovanej jednotky Krajského riaditeľstva Policajného zboru Bratislava kontrolovaný a vyzvaný, aby sa podrobil dychovej skúške prístrojom Alcotest 7510, sériové číslo I.-XXXX na zistenie prítomnosti etanolu v dychu s výsledkom dňa 22.06.2022 o 23:51 hod. v hodnote 0,60 mg/ l etanolu na liter vydychovaného vzduchu a s výsledkom opakovanej dychovej skúšky vykonanej dňa 23.06.2022 v čase o 00:22 hod. v hodnote 0,57 mg/l etanolu na liter vydychovaného vzduchu,"
44,n/a,other,truck,"že dňa 05.11.2022 v čase o 12:41 hod. v obci Staré Hory viedol po predchádzajúcom požití alkoholických nápojov nákladné motorové vozidlo zn. DAF ev. č. H. s návesom zn. Krone ev. č. H. po ceste I/59, kde bol pri Obecnom úrade Staré Hory zastavený a kontrolovaný policajtmi OR PZ v Banskej Bystrici, na výzvu ktorých sa v čase o 12:41 hod. podrobil dychovej skúške na prítomnosť alkoholu v dychu elektronickým prístrojom AlcoQuant 6020 plus č. A410244 s nameranou hodnotou 0,51 mg/l alkoholu v dychu a v čase o 12:51 hod. dňa 05.11.2022 s nameranou hodnotou 0,48 mg/l alkoholu v dychu,"
48,n/a,car,car,"dňa XX.XX.XXXX v čase o XX.XX h viedol v meste G. po M. ulici osobné motorové vozidlo zn. D. X., EČ: S po predchádzajúcom požití alkoholických nápojov, pričom bol zastavený a kontrolovaný hliadkou Obvodného oddelenia PZ G., ktorá u neho pri vykonanej dychovej skúške v uvedený deň v čase o XX.XX h namerala hodnotu 0,89 miligramu etanolu na liter vydýchnutého vzduchu a v čase o XX.XX. h hodnotu 0,89 miligramu etanolu na liter vydýchnutého vzduchu,"
52,n/a,car,car,"dňa 16.11.2022 v čase o 02,24 h, po tom, čo požil alkoholické nápoje a privodil si tak opilosť s hladinou 0,68 mg/l alkoholu v dychu, v takom stave v obci H., po ceste G./XXXX, okres P. viedol osobné motorové vozidlo zn. W. , EČ: XBPXXX, MPZ CZ, pričom jazdil zo strany na stranu, preto bol zastavený a kontrolovaný hliadkou PPZ Úradu hraničnej a cudzineckej polície, Oddelenia hraničnej kontroly P. Q.,"
61,car,n/a,car,"dňa 19. októbra 2022 v čase asi o 10:15 hod. riadil osobné motorové vozidlo značky Š. C., evidenčného čísla S.-XXXDP, po ceste č. G., smerom od F., kde v úseku cesty v obci D. H., časť M. M., okres F., pri rodinnom dome č. XX bol zastavený a kontrolovaný hliadkou Obvodného oddelenia PZ Púchov, pričom následne vykonanými dychovými skúškami na alkohol bolo zistené, že v čase vykonania dychových skúšok dňa 19.10.2022 o 10:20 hod. mal hladinu alkoholu v krvi zvýšenú na 0,50 mg/l, o 10:29 hod. na 0,47 mg/l a o 10:42 hod. na 0,46 mg/l,"
64,n/a,car,car,"dňa 26.01.2022 v čase po 22:10 h viedla osobné motorové vozidlo zn. Škoda Superb, ev. č.: K. XXX R. po ceste III/2026 a miestnych komunikáciách v obci G., okres Č., kde bola na križovatke ciest v časti zv. U. U. zastavovaná hliadkou OO PZ Turzovka, na zastavovanie nereagovala, s vozidlom unikala, pričom bola hliadkou OO PZ Turzovka prenasledovaná služobným motorovým vozidlom a zastavovaná za pomoci výstražného svetelného zariadenia s nápisom Stop, následkom čoho neskôr vozidlo zastavila pri ľavej krajnici pri radovej zástavbe domov v obci G., z vozidla vystúpila, dala sa na útek, pričom bola hliadkou polície naďalej prenasledovaná a následne pri miestnom potoku vypátraná a stotožnená, podrobila sa dychovej skúške s negatívnym výsledkom, ale keďže javila známky požitia omamných a psychotropných látok, bola vyzvaná na podrobenie sa lekárskemu vyšetreniu odberom krvi alebo iného biologického materiálu, či nie je ovplyvnená inou návykovou látkou, čo odmietla, hoci by to pri vyšetrení nebolo spojené s nebezpečenstvom pre jej zdravie a vozidlo viedla i napriek tomu, že Trestným rozkazom Okresného súdu Čadca sp. zn. 0T/70/2021 z 29.10.2021, ktorý nadobudol právoplatnosť 29.10.2021, jej bol uložený trest zákazu činnosti viesť motorové vozidlá na dobu 18 mesiacov a rozhodnutím o priestupku OR PZ, Okresného dopravného inšpektorátu Čadca pod č. p.: ORP-P-296/ODI-E-2020 z 08.10.2020, ktoré nadobudlo právoplatnosť 06.11.2020, jej bol uložený zákaz činnosti viesť motorové vozidlá na dobu 36 mesiacov odo dňa právoplatnosti rozhodnutia,"
66,car,van,car,"dňa 25.10.2022 v čase okolo 16:17 hod., po predchádzajúcom požití alkoholických nápojov, viedol motorové vozidlo značky Citroen Berlingo, EČV: A po miestnej komunikácii ulice Štefánikova v Námestove, smerom od predajne LIDL ku kruhovému objazdu, pričom keď sa s vozidlom nachádzal pred bytovým domom č. 214, bol hliadkou ODI Dolný Kubín zákonným spôsobom zastavený a kontrolovaný, kde sa podrobil dychovej skúške do analyzátora dychu AlcoQuant 6020 plus, sériové číslo A409032, ktorou mu bola nameraná dňa 25.10.2022 v čase o 16:19 hod. hodnota 0,80 mg/l alkoholu v dychu a dňa 25.10.2022 v čase o 16:37 hod. hodnota 0,96 mg/l alkoholu v dychu, a takto konal napriek tomu, že bol Rozsudkom Okresného súdu v Námestove, spisová značka 6T/114/2020, zo dňa 04.02.2021, ktoré nadobudlo právoplatnosť dňa 05.02.2021, odsúdený za prečin ohrozenia pod vplyvom návykovej látky podľa § 289 ods. 1 Trestného zákona,"
75,car,other,car,"dňa 06.11.2022 v čase asi o 01.50 hodine v Bratislave po petržalskom obchvate od Mosta Lafranconi v smere na Einsteinovu ulicu viedol, ako vodič, motorové vozidlo zn. T. N., ukrajinského evidenčného čísla T., pričom bol zastavený a kontrolovaný hliadkou policajného zboru, ktorá ho podrobila dychovej skúške, s ktorou súhlasil a v čase o 02.01 hodine dňa 06.11.2022 mu bola prístrojom AlcoQuant 6020 plus, sériové číslo A4409135 v dychu nameraná hodnota 0,57 mg/l alkoholu vo vydychovanom vzduchu, číslo merania 761, pričom pri opakovanej skúške vykonanej v čase o 02:22 hodine dňa 06.11.2022 tým istým prístrojom mu bola v dychu nameraná hodnota 0,52 mg/l alkoholu vo vydychovanom vzduchu, číslo merania 762,"
76,car,n/a,car,"dňa 19.10.2022 o 17.40 hodine viedol ako vodič osobné motorové vozidlo továrenskej značky W. D., G. W., evidenčného čísla A.-XXXDA po ceste III. triedy čísla XXXX, kde pred obcou H. D., okres Rimavská Sobota, bol zastavený a kontrolovaný hliadkou Obvodného oddelenia PZ Rimavská Sobota, pričom bol vyzvaný, aby ako vodič predložil potrebné doklady na vedenie a prevádzku vozidla, následne bol vyzvaný aby sa podrobil dychovej skúške na zistenie alkoholu meračom Alcotest 7410, evidenčného čísla ARFM 0034, kde mu bola v čase o 17.43 hodine nameraná hodnota 1,12 mg/l etanolu vo vydychovanom vzduchu (2,33 promile), ďalšou dychovou skúškou v čase o 18.07 hodine mu bola nameraná hodnota 1,12 mg/l etanolu vo vydychovanom vzduchu (2,33 promile) a opakovanou dychovou skúškou v čase o 18.34 hodine mu bola nameraná hodnota 1,09 mg/l etanolu vo vydychovanom vzduchu (2,27 promile),"
79,n/a,car,car,"v W. dňa XX.XX.XXXX v čase o XX:XX hod. viedla osobné motorové vozidlo zn. V., EČV: W. po ul. K., v smere do centra, kde pri P. I. bola zastavená, v stave vylučujúcom spôsobilosť, ktorú si privodila vplyvom návykovej látky - požitím alkoholických nápojov, pričom pri následnej kontrole hliadkou Obvodného oddelenia PZ Košice - U. sa podrobila dychovej skúške na zistenie prítomnosti alkoholu prístrojom H., ktorým jej bola nameraná hodnota alkoholu v dychu X,XX mg/l. v čase XX:XX. hod. a opakovanou dychovou skúškou v čase XX:XX hod. jej bola nameraná hodnota alkoholu X,XX mg/l"

### Span Attributes

In [421]:
attr = "DateOfOffense"
df_clean = df.replace("n/a", np.nan, inplace=False)
df_clean = df_clean.dropna(subset=[f"{attr}.text.0",f"{attr}.text.1", f"{attr}.llm"])

In [422]:
print(f"Evaluating all {len(df)} records")
print((df[f"{attr}.text.0"] == df[f"{attr}.text.1"]).sum()/len(df))
print((df[f"{attr}.text.0"] == df[f"{attr}.llm"]).sum()/len(df))
print((df[f"{attr}.text.1"] == df[f"{attr}.llm"]).sum()/len(df))

Evaluating all 202 records
0.8267326732673267
0.8811881188118812
0.8762376237623762

In [423]:
print(f"Evaluating only non-na {len(df_clean)} records")
print((df_clean[f"{attr}.text.0"] == df_clean[f"{attr}.text.1"]).sum()/len(df_clean))
print((df_clean[f"{attr}.text.0"] == df_clean[f"{attr}.llm"]).sum()/len(df_clean))
print((df_clean[f"{attr}.text.1"] == df_clean[f"{attr}.llm"]).sum()/len(df_clean))

Evaluating only non-na 167 records
0.9880239520958084
0.9640718562874252
0.9580838323353293

### Discrepancies

In [487]:
cols = [f"{attr}.text.0", f"{attr}.text.1", f"{attr}.llm"]
subset = df[cols + ["text"]]  # keep those 3 + the text column

# Keep only rows where not all values are the same
mask = subset[cols].nunique(axis=1) > 1
discrepancies = subset[mask]

display(discrepancies)

,TypeOfRoad.text.0,TypeOfRoad.text.1,TypeOfRoad.llm,text
0,ceste II. triedy,ceste II. triedy č. 532,class_II,"dňa 07.11.2022 v čase o 06:55 hod. v meste V. na ulici S.. V.. Š. po ceste II. triedy č. 532 viedol ako vodič osobné motorové vozidlo značky Škoda Octavia Combi, evidenčného čísla RA595AZ, po tom, čo požil alkoholické nápoje, pričom pred areálom spoločnosti MOSS.SK, s. r. o. Revúca bol zastavený a kontrolovaný hliadkou Okresného riaditeľstva Policajného zboru SR, Okresného dopravného inšpektorátu Revúca, kde vykonanou dychovou skúškou na zistenie prítomnosti alkoholu analyzátorom dychu typu „Dräger Alcotest 7510 classic“ výrobného čísla ARMF-0489 mu dňa 07.11.2022 o 06:56 hod. bolo nameraných 0,74 mg etanolu na liter vydychovaného vzduchu, čo je 1,54 promile,"
1,n/a,n/a,urban,"v Košiciach na ul. G. v smere od ul. F. E., dňa 1.11.2022 v čase okolo 02:37 hod. v stave vylučujúcom spôsobilosť viedol osobné motorové vozidlo zn. L. A., EVČ: L. XXXG., kde bol zastavený a kontrolovaný hliadkou Mestskej polície Košice a následne hliadkou OOPZ Košice - Západ, pričom bol podrobený dychovej skúške na určenie objemového percenta alkoholu v dychu prístrojom AlcoQuat 6020 plus, výrobné číslo A408921, pri ktorej mu bola nameraná pozitívna hodnota 0.58 mg/l,"
2,n/a,ulici Pionierska,urban,"dňa 31.10.2022 v čase o 01:30 hod. po predchádzajúcom požití alkoholických nápojov, bez dokladov potrebných k vedeniu a prevádzke motorového vozidla viedla osobné motorové vozidlo zn. Volkswagen Passat, ev. č. E. XXX C. po ulici Pionierska v Rajeckých Tepliciach, v smere jazdy od ulice Školskej ovplyvnená alkoholom v čase o 01:34 hod. vo výške 1,35 mg etanolu na liter vydychovaného vzduchu (čo predstavuje 2,81 promile), opakovanou dychovou skúškou jej bola v čase o 02:04 nameraná hodnota vo výške 1,45 mg etanolu na liter vydychovaného vzduchu (čo predstavuje 3,02 promile) a v čase o 03:10 hod. vo výške 1,20 mg etanolu na litere vydychovaného vzduchu (čo predstavuje 2,50 promile), pričom svojím konaním porušila ust. §4 ods. 1 písm. b); § 4 ods. 2 písm. d) Zákona č. 8/2009 Z.z. o cestnej premávke,"
3,n/a,ulici Poľná,n/a,", ž e - dňa 26. októbra 2022 po predchádzajúcom požití alkoholických nápojov viedol ako vodič motocykel značky Defender, bez evidenčného čísla v obci Tomášovce po ulici Poľná v smere na Ulicu SNP, kde bol pred rodinným domom číslo XXX v čase o 09:55 hodine zastavený a kontrolovaný hliadkou OR PZ ODI v Lučenci a počas kontroly bol vyzvaný, aby sa podrobil dychovej skúške na zistenie prítomnosti alkoholu v jeho dychu, čo po riadnom poučení vykonal a elektronickým prístrojom AlcoQuant 6020plus, evidenčného čísla A409594 mu bola dňa 26. októbra 2022 v čase o 10,00 hodine nameraná hodnota 1,15 miligramu na liter vydychovaného etanolu v dychu,"
5,n/a,n/a,urban,"dňa XX.XX.XXXX v čase o XX:XX V.. po predchádzajúcom požití alkoholických nápojov viedol osobné motorové vozidlo značky K. L. ev. č.: O., po ulici H.. L. P. T., kde bol príslušníkmi OO PZ T.-P. pri bytovom dome č. XX, zastavený a okrem iného vyzvaný k podrobeniu sa dychovej skúške na zistenie prítomnosti alkoholu vo vydychovanom vzduch prístrojom H. XXXX, výrobné číslo H. XXXX, čo i vykonal a v dychu obvineného bola zistená prítomnosť alkoholu v čase o XX:XX hod. v objeme 0,86 mg/l (1,79 ‰) a v čase o 20:25 hod. v objeme 0,81 mg/l (1,69 ‰),"
6,n/a,ulici J.,urban,"dňa 24.10.2022 v čase o 14.20 h v meste Q. okr. Q. po predchádzajúcom požití alkoholických nápojov, viedla ako vodička osobné motorové vozidlo továrenskej značky M. N., Y.. Č..: Q., L.. G., v meste Q. po ulici J. C. v smere od U. E. smerom na Q. D., kde bola pri firme E. E. zákonným spôsobom zastavená a kontrolovaná hliadkou Oddelenia železničnej Polície Zvolen, pričom pri kontrole bola poučená a vyzvaná, aby sa podrobila dychovej skúške analyzátorom dychu AlcoQuant 6020 plus, evidenčné číslo A409058, ktorým sa určí objemové percento alkoholu v dychu, ktorú neodmietla a tejto sa dobrovoľne podrobila a dychovou skúškou jej bola dňa 24.10.2022 v čase o 14.24 h zistená hodnota 0,67 mg etanolu na liter vydychovaného vzduchu a opakovanou dychovou skúškou dňa 24.10.2022 v čase o 15.02 h vykonanou tým istým prístrojom jej bola zistená hodnota 0,57 mg etanolu na liter vydychovaného vzduchu"
7,I. triedy,XX,class_I,"dňa XX. XX. XXXX v čase o XX.XX hod. viedol ako vodič osobné motorové vozidlo zn. BMW ev. č. T. po ceste I. triedy č. XX po ul. Š. v meste C., kde bol predpísaným spôsobom zastavovaný, pričom na tieto výzvy vôbec nereagoval, naopak zrýchlil a v jazde pokračoval ďalej až na ul. R., kde pred rodinným domom č. 271/2 vozidlo zastavil, vyskočil z vozidla a začal utekať preč, pričom bol následne hliadkou OO PZ v Tornali spacifikovaný a pri služobnom zákroku bol použitý varovný výstrel do vzduchu, donucovacie prostriedky hmaty, chmaty a služobné putá a pri kontrole sa na výzvu policajta dňa XX. XX. XXXX v čase o XX.XX hod. odmietol podrobiť dychovej skúške na zistenie, či nie je ovplyvnený návykovou látkou analyzátorom dychu AlcoQuant 6020 plus výr. č. A409739 a taktiež sa odmietol podrobiť lekárskemu vyšetreniu odberom a vyšetrením krvi alebo iného biologického materiálu, hoci by to pri vyšetrení nebolo spojené s nebezpečenstvom pre jeho zdravie, následne pred umiestnením do cely policajného zaistenia zriadenej na OO PZ v Revúcej bol dňa XX. XX. XXXX v čase o XX.XX hod. podrobený dyhovej skúške analyzátorom dychu AlcoQuant 6020 plus výr. č. A408962, ktorým mu bola nameraná hodnota 0,71 miligramu etanolu na liter vydychovaného vzduchu, čo je pozitívny výsledok,"
8,n/a,ceste I/64,class_I,": ako vodič bez vodičského oprávnenia po tom, čo požil alkoholické nápoje viedol dňa 30.10.2022 v čase o 19:19 h v obci Preseľany na ceste I/64, viedol osobné motorové vozidlo továrenskej značky Škoda Octavia, evidenčného čísla NR-XXXKR. kde počas jazdy bol v obci L. na ceste I/64 pred pizzeriou H. zastavený a kontrolovaný hliadkou ODI OR PZ Topoľčany, pričom vykonanou dychovou skúškou do prístroja Drager 7510, číslo H.-XXXX, číslo merania XXXX mu bola v čase o 19:19 h nameraná hodnota 1,02 miligramu etanolu na liter vydýchnutého vzduchu,"
9,n/a,ceste II/519,class_II,", ž e - dňa 17.12.2021 v čase približne o 19:00 hod. viedol ako vodič motorové vozidlo zn. C. S., ev. č. S. po ceste II/519 v smere od obce Slovenské Pravno do obce Rudno, kde pri kilometrovníku 13,0 zišiel s vozidlom mimo cestu vľavo, pričom z miesta odišiel a následne, keď sa k motorovému vozidlu zn. C. S., ev. č. S. vrátil, bol po riadnom poučení vyzvaný, aby sa podrobil dychovej skúške na zistenie požitia alkoholu do elektronického prístroja Alcotest 7510, výrobné číslo ARMF-0427, kde metódou merania etanolu vo vydychovanom vzduchu mu bola dňa 17.12.2021 v čase o 20:47 hod. nameraná hodnota 1,07 mg/l alkoholu vo vydychovanom vzduchu, čo v prepočte predstavuje 2,23 ‰, opakovanou dychovou skúškou dňa 17.12.2021 v čase o 21:03 hod. nameraná hodnota 1,10 mg/1 alkoholu vo vydychovanom vzduchu, čo v prepočte predstavuje 2,29 ‰ a ďalšou opakovanou dychovou skúškou dňa 17.12.2021 v čase o 21:19 hod. nameraná hodnota 1,01 mg/l alkoholu vo vydychovanom vzduchu, čo v prepočte predstavuje 2,10 ‰, pričom na základe odborného vyjadrenia znalca prof. MUDr. Ľ. X., PhD. zo dňa 30.12.2021 vyplýva, že koncentrácia alkoholu v krvi obvineného bola dňa 17.12.2021 v čase o 19:00 hod. minimálne vo výške 1,33 až 1,48 ‰,"
10,n/a,n/a,urban,", že dňa 17.11.2022 v čase o 11.05 h. v Senci, na Farskom námestí viedol osobné motorové vozidlo zn. BMW, modrej metalízy, EČ: DS-XXXHN, následne zastal s vozidlom na stredovej časti vozovky a obsluhoval mobilný telefón, čím blokoval prejazd vozidiel, po spozorovaní hliadky PZ sa pohol s vozidlom, následne bol predpísaným spôsobom zastavený a kontrolovaný hliadkou PMJ KR PZ Bratislava, pričom javil známky požitia omamných a psychotropných látok, následne bol vyzvaný k podrobeniu sa lekárskemu vyšetreniu na zistenie omamných a psychotropných látok, čo aj napriek po opakovanom poučení odmietol, načo následné išiel s hliadkou PZ na Centrálny príjem Nemocnice svätého Michala v Bratislave, na Satinského ul. č. 1, kde sa pred službukonajúcim lekárom MUDr. C. A. O. v čase o 12.27 h dňa 17.11.2022 odmietol podrobiť odberu biologického materiálu na zistenie prítomnosti omamných a psychotropných látok v krvi,"
11,M.,M,urban,", ž e v B., po ul. M. Č.. XX, dňa 29.10.2022 o 22:40 hod. viedol osobné motorové vozidlo továrenskej značky F. U. evidenčného čísla B. XXX I., pričom bol hliadkou Okresného riaditeľstva Policajného zboru v B., Odboru poriadkovej polície, Obvodného oddelenia Policajného zboru B. - P. v rámci výkonu dohľadu nad bezpečnosťou a plynulosťou v cestnej doprave zastavený a vyzvaný, aby sa podrobil dychovej skúške na prítomnosť alkoholu v dychu, ktorú odmietol, následne bol hliadkou polície vyzvaný, aby sa podrobil lekárskemu vyšetreniu spojenému s odberom a laboratórnym vyšetrením krvi alebo iného biologického materiálu, ktoré takisto odmietol, čím takto neuposlúchol výzvu policajta v zmysle ustanovenia § 3 ods. 2 písm. c/ zákona č. 8/2009 Z.z. o cestnej premávke a o zmene a doplnení niektorých zákonov v znení neskorších predpisov,"
12,miestnej komunikácii,miestnej komunikácii,urban,", ž e dňa 06. novembra 2022 v čase okolo 22:40 hod. na miestnej komunikácii v obci Kluknava z parkoviska pod kaštieľom na parkovisko pred predajňou CBA a následne po parkovisku pred predajňou CBA, po predchádzajúcom požití alkoholu, ktorým sa priviedol do stavu vylučujúceho spôsobilosť bezpečne viesť motorové vozidlá, viedol osobné motorové vozidlo továrenskej značky Volkswagen Golf, evidenčného čísla J. XXX F., pričom dychovou skúškou elektronickým prístrojom AlcoQuant 6020 plus mu bola nameraná hodnota 1,27 mg/l alkoholu v dychu,"
13,n/a,n/a,urban,"dňa XX.XX.XXXX v čase približne o XX:XX hod. v obci G. Y. smerom na obec S. riadil osobné motorové vozidlo zn. S. D., ev. č. BN XXX CH, kde bol pred domom č. XXX zastavený a kontrolovaný hliadkou OR PZ O. nad O., v rámci kontroly sa podrobil dychovej skúške, ktorú vykonal s negatívnym výsledkom, nakoľko však javil známky požitia omamných a psychotropných látok bol následne uvedenou hliadkou vyzvaný na podrobenie sa lekárskemu vyšetreniu odberom krvi a iného biologického materiálu, ktorému sa dňa XX.XX.XXXX v čase o XX:XX hod. dobrovoľne podrobil a z výsledkov laboratórnych vyšetrení toxikologicko-chemickej analýzy vykonanou v W. a patologicko anatomickom pracovisku O. O. bola v jemu odobratej vzorke krvi zistená prítomnosti metamfetamínu v koncentrácii XXXX ng/ml a amfetamínu v koncentrácii XXX ng/ml, pričom v zmysle zákona NR SR č. XXX/XXXX Z. z. o omamných látkach, psychotropných látkach a prípravkoch v znení neskorších predpisov sú metamfetamín a amfetamín zaradené do II. skupiny psychotropných látok, a toto u neho vyvolalo stav ťažkého stupňa opitosti s približnou koncentráciou alkoholu v krvi okolo X,X promile a viac,"
14,n/a,ulici Q,urban,", ž e obvinený T. D. dňa 19. novembra 2021 v čase okolo 20.46 h v X. A. Q., okres X. A. Q., na ulici Q. po predchádzajúcom požití konope (marihuany) viedol osobné motorové vozidlo továrenskej značky Q. F., evidenčného čísla LE XXXAN, kde bol na ulici Q. zastavený a kontrolovaný policajnou hliadkou nakoľko počas policajnej kontroly javil známky požitia omamných a psychotropných látok, bol mu v čase o 23.13 hod. uvedeného dňa odobratý biologický materiál krv a moč, pričom imunochromatografickým skríningom mu bola v krvi zistená konfirmácia delta-9-tetrahydrokanabinolu (THC) v hodnote 12,66 ng/ml, pričom THC je hlavnou psychoaktívnou látkou rastlín konope, ktoré sú zaradené do I. skupiny omamných látok a THC do I. skupiny psychotropných látok podľa zákona č. 139/1998 Z. z. o omamných látkach, psychotropných látkach a prípravkov v znení neskorších predpisov a podľa znaleckého posudku z odvetvia psychiatria mal v čase jazdy hladinu THC v tele jednoznačne nad toxickým limitom, v dôsledku čoho jeho psychické a fyzické funkcie boli v stave vylučujúcom viesť motorové vozidlo, obvinený A. U. P. v presne nezistenej dobe, na presne nezistenom mieste v meste O., okres O. od neznámej osoby zakúpil vysušené vrcholky rastliny konope (Cannabis), z ktorých časť skonzumoval a následne prechovával po akúkoľvek dobu na bližšie nezistených miestach pri sebe až do cestnej kontroly osobného motorového vozidla továrenskej značky Q. F. evidenčného čísla LE XXXAN, v ktorom sa ako spolujazdec prepravoval dňa 19. novembra 2021 v čase o 23.03 hod. v meste X. A. Q. na ulici Q., okres X. A. Q. po ktorej dňa 20. novembra 2021 v čase o 03.00 hod., vydal polícii 2 igelitové vrecúška s obsahom vysušených vrcholkov rastliny konope (Cannabis) o celkovej hmotnosti 172,11 gramov s priemernou koncentráciou od 7,9% do 10,3% hmotnostných THC (tetrahydrokanabinolu), čo zodpovedá najmenej 344 bežným jednotlivým dávkam drogy, schopných ovplyvniť psychiku užívateľa (konzumenta), pričom rastliny rodu Cannabis (konope) sú v zmysle zákona Národnej rady Slovenskej republiky č. 139/1998 Z.z. o omamných látkach, psychotropných látkach a prípravkoch v znení neskorších predpisov zaradené do I. skupiny omamných látok a účinná látka tetrahydrokanabinol (THC) do I. skupiny psychotropných látok, obvinený T. H. v presne nezistenej dobe, na presne nezistenom mieste, od bližšie nestotožnenej osoby zadovážil vysušené vrcholky rastliny konope (Cannabis), z ktorých časť skonzumoval a následne prechovával po akúkoľvek dobu na bližšie nezistených miestach v X. A. Q., pri sebe a taktiež dňa 19. novembra 2021 vo večerných hodinách ešte zakúpil od nestotožnenej osoby v X. A. Q., okres X. A. Q. na sídlisku P., pri kine P., vysušené vrcholky rastliny konope (Cannabis), ktoré následne prechovával pri sebe až do cestnej kontroly osobného motorového vozidla továrenskej značky Q. F. evidenčného čísla LE XXXAN, v ktorom sa ako spolujazdec prepravoval dňa 19. novembra 2021 v čase o 23.03 hod. v meste X. A. Q., na ulici Q., po ktorej dňa 20. novembra 2021 v čase o 03.00 hod. vydal polícii 2 igelitové vrecúška s obsahom vysušených vrcholkov rastliny konope (Cannabis) o celkovej hmotnosti 69,62 gramov s priemernou koncentráciou od 7,7% do 9,8% hmotnostných THC (tetrahydrokanabinolu), čo zodpovedá najmenej 139 bežným jednotlivým dávkam drogy, schopných ovplyvniť psychiku užívateľa (konzumenta), pričom rastliny rodu Cannabis (konope) sú v zmysle zákona Národnej rady Slovenskej republiky č. 139/1998 Z.z. o omamných látkach, psychotropných látkach a prípravkoch v znení neskorších predpisov zaradené do I. skupiny omamných látok a účinná látka tetrahydrokanabinol (THC) do I. skupiny psychotropných látok,"
15,ceste číslo I/18,ceste číslo I/18 - Prosbenová\ncesta,class_II; class_I,", ž e dňa 04. novembra 2022 v čase okolo 13:22 hod. v meste Levoča po ceste číslo II/533, Novoveská cesta po kruhovom objazde a následne v smere jazdy z kruhového objazdu po ceste číslo I/18 - Prosbenová cesta viedol osobné motorové vozidlo značky Dacia Logan s evidenčným číslom U., kde bol v čase o 13:25 hod. zastavený a hliadkou PZ po zákonnom poučení, vyzvaný k podrobeniu sa dychovej skúške na zistenie požitia alkoholu v dychu, ktorej sa bezdôvodne odmietol podrobiť, následne bol vyzvaný k podrobeniu sa lekárskemu vyšetreniu odberom biologického materiálu na zistenie prítomnosti alkoholu v krvi, čo taktiež bezdôvodne odmietol, napriek tomu, že by to nebolo spojené s nebezpečenstvom pre jeho zdravie a takto konal napriek tomu, že trestným rozkazom Okresného súdu Košice - okolie sp. zn. 0T/96/2021 zo dňa 06.11.2021, ktorý nadobudol právoplatnosť dňa 06.11.2021, mu bol uložený aj trest zákazu činnosti viesť všetky druhy motorových vozidiel v trvaní 28 mesiacov, od 06.11.2021 do 06.03.2024,"
16,n/a,na ulicu Q,urban,"dňa 05.11.2022, v čase pred 19.10 hod., v K., riadil po ulici Z., v smere od centra mesta na obec J. osobné motorové vozidlo zn. P. K., ev. č. H. kde na kruhovej križovatke pri OD Tesco, odbočil na ulicu Q., kde bol zastavený a kontrolovaný hliadkou Obvodného oddelenia PZ Púchov, na ktorej výzvu sa odmietol podrobiť vyšetreniu na zistenie alkoholu dychovou skúškou a aj lekárskemu vyšetreniu spojenému s odberom a vyšetrením krvi alebo iného biologického materiálu, za účelom zistenia či nie je ovplyvnený návykovou látkou, hoci toto vyšetrenie nebolo spojené s nebezpečenstvom pre jeho zdravie,"
17,n/a,n/a,urban,": po tom, čo požil alkoholické nápoje, dňa XX.XX.XXXX približne o XX.XX hod. v W. na ulici J. H. smerom na ul. X. , ako vodič viedol osobné motorové vozidlo továrenskej značky D. S., evidenčného číslo U kde počas jazdy bol na ulici X. pred obytným domom č. XXXX zastavený a kontrolovaný hliadkou príslušníkov K. oddelenia PZ W., pričom vykonanou dychovou skúškou do prístroja D. G. XXXX, číslo G.-XXXX, číslo merania XXXXX, bola u neho v čase o XX.XX hod. dňa XX.XX.XXXX nameraná hodnota X,XX miligramu etanolu na liter vydýchnutého vzduchu,"
18,n/a,n/a,urban,"že dňa 09.11.2022 v čase o 22.50 hod. po predchádzajúcom požití alkoholu viedol osobné motorové vozidlo zn. Škoda Felicia e. č. W.-XXX P. po ulici Rudnej v obci Nižnoslanská Baňa, okres Rožňava, kde bol z dôvodu, že nepoužíval znamenie o zmene smeru jazdy hliadkou OO PZ Dobšiná predpísaným spôsobom zastavený, pričom vykonanou dychovou skúškou bolo v čase o 22.35 hod. prístrojom AlcoQuant 6020 plus zistené, že v čase vedenia motorového vozidla mal v jednom litri ním vydychovaného vzduchu najmenej 0,66 mg/l alkoholu"
19,ceste III/2306,n/a,other,"dňa 23.10.2022 v čase o 15.20 hod. v stave vylučujúcom spôsobilosť viedol osobné motorové vozidlo značky Škoda Octavia Combi, červenej farby s EVČ: V po ceste III/2306 v obci Brezovica v smere od mesta Trstená k obecnému úradu, kde bol službukonajúcou hliadkou Obvodného oddelenia PZ Trstená predpísaným spôsobom pri budove s popisným číslom 43/68 zastavený a kontrolovaný, pričom počas kontroly sa podrobil dychovej skúške do elektronického merača zn. AlcoQuant 6020 plus, sériové číslo: A410037, ktorý dňa 23.10.2022 v čase o 15.25 hod. nameral hodnotu 0,55 mg/l alkoholu v dychu a dňa 23.10.2022 v čase 15:41 hod. nameral hodnotu 0,57 mg/l alkoholu v dychu,"
20,v obci,n/a,urban,": ako vodič po tom, čo požil alkoholické nápoje dňa 16.10.2022 v čase o 21:40 h v obci S., okres T., na ulici K., viedol osobné motorové vozidlo továrenskej značky A. J. J., evidenčného čísla T kde počas jazdy bol v obci S. na ul. K. pri rodinnom dome č. XXX/XXX zastavený a kontrolovaný hliadkou OO PZ Topoľčany, pričom vykonanou dychovou skúškou do prístroja O. XXXX plus, číslo O číslo merania XXXX mu bola v čase o 21:42 h nameraná hodnota 0,67 miligramu etanolu na liter vydýchnutého vzduchu,"
21,pozemnej komunikácií,n/a,other,"dňa 15. 11. 2022 v čase o 18.26 hodine na pozemnej komunikácií v obci Zlaté Klasy, na Seneckej ceste pred rodinným domom so súpisným číslom 1067, okres Dunajská Streda, po predchádzajúcom požití presne nezisteného množstva alkoholických nápojov ako vodič viedol osobné motorové vozidlo značky Renault Megane s evidenčným číslom W.-XXXHY šedej farby, pričom bol riadne zastavený hliadkou Obvodného oddelenia Policajného zboru Šamorín a nakoľko počas kontroly javil známky požitia alkoholických nápojov, po zákonnom poučení bol podrobený dychovej skúške elektronickým meračom typu Alcotest 7510 elassie, číslo prístroja ARMF-0550, ktorým mu v čase 0 18.26 hod. dňa 15.11. 2022 bola nameraná hodnota 0,79 mg/l alkoholu v dychu (v prepočte 1 ,65 promile),"
23,n/a,/XXXX,n/a,"dňa XX.XX.XXXX v čase o XX.XX h viedol po ceste P./XXXX medzi mestom R. a obcou N. E. v okrese F. osobné motorové vozidlo zn. S. XXX, EČ: F po predchádzajúcom požití alkoholických nápojov, pričom bol zastavený a kontrolovaný hliadkou Obvodného oddelenia PZ R., ktorá u neho pri vykonanej dychovej skúške v uvedený deň v čase o XX.XX h namerala hodnotu 0,88 miligramu etanolu na liter vydýchnutého vzduchu a v čase o XX.XX h hodnotu 0,85 miligramu etanolu na liter vydýchnutého vzduchu,"