# Attribute extraction pipeline

## Expert-based extraction

In [3]:
from google import genai
from google.genai import types
import os
client = genai.Client(api_key=os.environ["GENAI_API_KEY"])

In [1]:
dataset_name = "../data/categorization/DKK-other-final.csv"

In [8]:
import json 
def get_json(string):
    stripped = ""
    braces = 0
    for s in string:
        if s == "{":
            braces += 1
        if braces >= 1:
            stripped += s
        if s == "}":
            braces -= 1
    return json.loads(stripped, strict=False)

In [3]:
import pandas as pd
import csv
import sys
csv.field_size_limit(sys.maxsize)

df = pd.read_csv(
    dataset_name,
    sep=",",
    quoting=1,  # csv.QUOTE_ALL
    quotechar='"',
    escapechar="\\",
    engine="python"  # Required when dealing with multiline quoted fields
)

# Check the first few rows
marenky = df[df["judgement_model_short"] == "A"]
pod_vlivem = df[df["judgement_model_short"] == "B"]
s_nasledkem = df[df["judgement_model_short"] == "C"]
jina = df[df["judgement_model_short"] == "D"]
nedopravni = df[df["judgement_model_short"] == "E"]

In [13]:
print(f"Violation of a driving ban: {len(marenky)}")
print(f"Drug-impaired driving: {len(pod_vlivem)}")
print(f"Traffic-related injury: {len(s_nasledkem)}")
print(f"Other traffic offenses: {len(jina)}")
print(f"Non-traffic offenses: {len(nedopravni)}")

Violation of a driving ban: 369
Drug-impaired driving: 1775
Traffic-related injury: 983
Other traffic offenses: 103
Non-traffic offenses: 6740

## Violation of a driving ban

In [11]:

MARENKY_STRUCTURED = {}
MARENKY_EXTRA = {}

In [12]:
def extract(marenka):
    print(marenka["judgement_slt_id"])
    print(marenka["judgement_factual_sentence"])
    chat = client.chats.create(model="gemini-2.5-flash", config=types.GenerateContentConfig(system_instruction="""You extract values for attributes from text. The texts are the factual statements in court verdicts. Return only information from the text, never make stuff up. If the value for attribute is not provided, return value 'n/a'. The date format id DD.MM.YYYY.  The time format is HH:MM. Decimal number are rounded to two digits after the decimal point: #.##. Format your output as JSON. The values mut be in the original language - Slovak. Extract the follwing attributes:
            revokingAuthority [Authority that revoked the driving license]  
            authorityLocation [Location of the authority that revoked the license]  
            revocationDateLegalEffect [Date when the license revocation became legally binding]  
            decisionDate [Date of the decision]  
            revocationDuration [For how long the license was revoked]  
            dateOfOffense [Date when the offense occurred]  
            timeOfOffense [Time when the offense occurred]  
            placeOfOffense [A name of the city/town where the offense occurred]
            placeDetails [Details about where the offense occurred]
            vehicleModel [Vehicle brand and model involved in the offense, e.g Škoda Octavia, or "anonymized" if only capital letters are provided]
            vehicleType [Type of vehicle involved in the offense]
            checkedBy [Who conducted the inspection or check]  
            typeOfDrivingBan [Type of driving ban / which vehicles are affected]  
            typeOfRoad [Type of road where the offense occurred]  
            reasonForRevocation [Reason for revoking the driving license]  
            additionalViolations [Additional traffic law violations] 

            The placeOfOffense is coded as follows:
            [name of the town/city in Slovak]
            outside town/city limits (if offence occurs outside of any municipality)
            anonymized (e.g. v obci A.B.)
            n/a (if the information in not provided)

            The vehicleType is coded as follows:
            car
            van
            truck
            bus
            motorcycle
            other

            The typeOfRoad is coded as follows:
            urban
            motorway
            class_I
            class_II
            other
            n/a (if the information in not provided)
            """),
       )
    
    response = chat.send_message(marenka["judgement_factual_sentence"])
    MARENKY_STRUCTURED[marenka["judgement_slt_id"]] = get_json(response.text)
    
    print(f"ATTRIBUTES:\n{response.text}")
    
    #response = chat.send_message("What other information was there in the statenent but is not covered by the attributes? Write is in a structured way as JSON (without high level attribute, e.g. OtherInformatio). Only output information from the original text.  The keys must be in English, the values mut be in the original language - Slovak.")
    #MARENKY_EXTRA[marenka["judgement_slt_id"]] = get_json(response.text)
 
    response = chat.send_message("What other information was there in the statenent but is not covered by the attributes? Write one sentence containing the extra information. Output a json with one atttribute: 'note' wherethe value is the sentence with extra information. Only output information from the original text. The sentence mut be in the original language - Slovak.")
    MARENKY_STRUCTURED[marenka["judgement_slt_id"]]["note"] = get_json(response.text)["note"]
    MARENKY_STRUCTURED[marenka["judgement_slt_id"]]["sentence"] = marenka["judgement_factual_sentence"]
    
    
    print(f"EXTRA:\n{response.text}")

In [84]:
for i in range(len(marenky)): 
    marenka = marenky.iloc[i]
    extract(marenka)

2154941
, ž e  dňa 30.07.2017 v čase o 8:23 hod. viedol na ceste II. triedy č. 425 na hraničnom prechode Brodské - Lanžhot osobné motorové vozidlo zn. C. N., EČV: XBXXXXX, kde bol zastavený a kontrolovaný hliadkou OO PZ Brodské, pričom kontrolou bolo zistené, že viedol motorové vozidlo i napriek tomu, že má rozsudkom Okresného súdu Senica sp.zn. 1T/96/2014 zo dňa 27.10.2014, právoplatný 27.10.2014 uložený zákaz činnosti viesť motorové vozidlá na dobu 12 (dvanásť) mesiacov, ktorý mu začal plynúť až po prepustení z ÚVTOS na slobodu dňa 27.12.2016,
ATTRIBUTES:
```json
{
  "revokingAuthority": "Okresný súd Senica",
  "authorityLocation": "Senica",
  "revocationDateLegalEffect": "27.10.2014",
  "decisionDate": "27.10.2014",
  "revocationDuration": "12 mesiacov",
  "dateOfOffense": "30.07.2017",
  "timeOfOffense": "08:23",
  "placeOfOffense": "Brodské",
  "placeDetails": "na ceste II. triedy č. 425 na hraničnom prechode Brodské - Lanžhot",
  "vehicleModel": "anonymized",
  "vehicleType": "car",
  "checkedBy": "hliadkou OO PZ Brodské",
  "typeOfDrivingBan": "zákaz činnosti viesť motorové vozidlá",
  "typeOfRoad": "class_II",
  "reasonForRevocation": "viedol motorové vozidlo i napriek tomu, že má uložený zákaz činnosti viesť motorové vozidlá",
  "additionalViolations": "n/a"
}
```
EXTRA:
```json
{
  "note": "Zákaz činnosti viesť motorové vozidlá mu začal plynúť až po prepustení z ÚVTOS na slobodu dňa 27.12.2016."
}
```
1636460
dňa 22.01.2018 v čase okolo 23.10 h v Stupave smere zo Zdravotníckej ulice na Hlavnú ulicu, ako vodič
viedol osobné motorové vozidlo značky X. D., e.č.: BA-XXXNZ, pričom uvedeného konania sa dopustil
aj napriek tomu, že mal vedomosť o tom, že v danom čase mu bol Trestným rozkazom Okresného súdu
Bratislava II 0T/357/2017 zo dňa 25.10.2017, právoplatný dňa 25.10.2017, uložený trest zákazu činnosti
viesť motorové vozidlá akéhokoľvek druhu po dobu 36 mesiacov,
ATTRIBUTES:
```json
{
  "revokingAuthority": "Okresného súdu Bratislava II",
  "authorityLocation": "Bratislava II",
  "revocationDateLegalEffect": "25.10.2017",
  "decisionDate": "25.10.2017",
  "revocationDuration": "36 mesiacov",
  "dateOfOffense": "22.01.2018",
  "timeOfOffense": "23:10",
  "placeOfOffense": "Stupava",
  "placeDetails": "smere zo Zdravotníckej ulice na Hlavnú ulicu",
  "vehicleModel": "anonymized",
  "vehicleType": "car",
  "checkedBy": "n/a",
  "typeOfDrivingBan": "akéhokoľvek druhu",
  "typeOfRoad": "urban",
  "reasonForRevocation": "Viedol motorové vozidlo napriek tomu, že mu bol uložený trest zákazu činnosti viesť motorové vozidlá akéhokoľvek druhu.",
  "additionalViolations": "n/a"
}
```
EXTRA:
```json
{
  "note": "Trestný rozkaz mal číslo 0T/357/2017 a vozidlo malo evidenčné číslo BA-XXXNZ."
}
```
2162446
aj napriek tomu, že rozhodnutím Okresného dopravného inšpektorátu Michalovce sp.zn. M.-MI-M zo dňa 06.09.2017, ktoré nadobudlo právoplatnosť dňa 28.09.2017 mu bol za priestupok proti bezpečnosti a plynulosti cestnej premávky podľa § 22 ods. 1 písm.k/ zák. SNR č. 372/1990 Zb. o priestupkoch v znení neskorších predpisov uložený okrem iného aj zákaz činnosti viesť motorové vozidlo na dobu 12 mesiacov, nerešpektujúc toto rozhodnutie dňa 30.01.2018 v čase o 14,30 h po štátnej ceste III/050218 v obci Žbince v smere od základnej školy smerom k rómskej osade viedol osobné motorové vozidlo zn. T. D., EČ: HE XXXCD, kde bol zastavený pretože mu na vozidle nesvietili stretávacie svetlá a kontrolovaný policajnou hliadkou, ktorá mu v ďalšej jazde zakázala pokračovať,
ATTRIBUTES:
```json
{
  "revokingAuthority": "Okresného dopravného inšpektorátu Michalovce",
  "authorityLocation": "Michalovce",
  "revocationDateLegalEffect": "28.09.2017",
  "decisionDate": "06.09.2017",
  "revocationDuration": "12 mesiacov",
  "dateOfOffense": "30.01.2018",
  "timeOfOffense": "14:30",
  "placeOfOffense": "Žbince",
  "placeDetails": "v smere od základnej školy smerom k rómskej osade",
  "vehicleModel": "anonymized",
  "vehicleType": "car",
  "checkedBy": "policajnou hliadkou",
  "typeOfDrivingBan": "viesť motorové vozidlo",
  "typeOfRoad": "class_III",
  "reasonForRevocation": "priestupok proti bezpečnosti a plynulosti cestnej premávky podľa § 22 ods. 1 písm.k/ zák. SNR č. 372/1990 Zb. o priestupkoch v znení neskorších predpisov",
  "additionalViolations": "nesvietili stretávacie svetlá"
}
```
EXTRA:
```json
{
  "note": "Rozhodnutie Okresného dopravného inšpektorátu Michalovce malo spisovú značku M.-MI-M, vozidlo malo EČ: HE XXXCD a policajná hliadka mu v ďalšej jazde zakázala pokračovať."
}
```
1638701
dňa 25.01.2018 v čase okolo 02.50 h v Stupave na Železničnej ulicu, ako vodič viedol osobné motorové
vozidlo mačky O. T., e.č.: MA-XXX DB, pričom uvedeného konania sa dopustil aj napriek tomu, že mal
vedomosť o tom, že v danom čase mu bol Trestným rozkazom Okresného súdu Malacky 0T/41/2017
zo dňa 19.05.2017, právoplatný dňa 19.05.2017, uložený trest zákazu činnosti viesť motorové vozidlá
akéhokoľvek druhu po dobu 15 mesiacov,
ATTRIBUTES:
```json
{
  "revokingAuthority": "Okresný súd Malacky",
  "authorityLocation": "Malacky",
  "revocationDateLegalEffect": "19.05.2017",
  "decisionDate": "19.05.2017",
  "revocationDuration": "15 mesiacov",
  "dateOfOffense": "25.01.2018",
  "timeOfOffense": "02:50",
  "placeOfOffense": "Stupava",
  "placeDetails": "Železničná ulica",
  "vehicleModel": "anonymized",
  "vehicleType": "car",
  "checkedBy": "n/a",
  "typeOfDrivingBan": "viesť motorové vozidlá akéhokoľvek druhu",
  "typeOfRoad": "urban",
  "reasonForRevocation": "Viedol motorové vozidlo napriek právoplatnému zákazu činnosti viesť motorové vozidlá",
  "additionalViolations": "n/a"
}
```
EXTRA:
```json
{
  "note": "Vozidlo malo e.č.: MA-XXX DB a zákaz činnosti bol uložený Trestným rozkazom Okresného súdu Malacky s označením 0T/41/2017."
}
```
2221001
i napriek tomu, že trestným rozkazom Okresného súdu Námestovo sp. zn. 4T 97/2015 zo dňa 25.2.2016, ktorý nadobudol právoplatnosť 12.3.2016, mu bol okrem iného uložený trest zákazu činnosti viesť motorové vozidlá po dobu 40 (štyridsať) mesiacov, dňa 19.1.2018 v čase okolo 13.33 hodine viedol malotraktor značky KUBOTA zvláštneho ev.č. C 54480 po ulici Oravickej v Trstenej, pričom pri rodinnom dome číslo XXX/XX bol zastavená a kontrolovaný hliadkou Obvodného oddelenia PZ Trstená,
ATTRIBUTES:
```json
{
  "revokingAuthority": "Okresný súd Námestovo",
  "authorityLocation": "Námestovo",
  "revocationDateLegalEffect": "12.03.2016",
  "decisionDate": "25.02.2016",
  "revocationDuration": "40 mesiacov",
  "dateOfOffense": "19.01.2018",
  "timeOfOffense": "13:33",
  "placeOfOffense": "Trstená",
  "placeDetails": "na ulici Oravickej pri rodinnom dome číslo XXX/XX",
  "vehicleModel": "KUBOTA",
  "vehicleType": "other",
  "checkedBy": "hliadka Obvodného oddelenia PZ Trstená",
  "typeOfDrivingBan": "všetky motorové vozidlá",
  "typeOfRoad": "urban",
  "reasonForRevocation": "Šoférovanie počas zákazu činnosti",
  "additionalViolations": "n/a"
}
```
EXTRA:
```json
{
  "note": "Ďalšie informácie v texte, ktoré neboli pokryté, sú spisová značka súdneho rozhodnutia sp. zn. 4T 97/2015 a špeciálne evidenčné číslo vozidla C 54480."
}
```
1641467
, že dňa 1. februára 2018 v čase o 17.32 hodine v meste Komárno viedol po Eötvösovej ulici osobné motorové vozidlo značky Ford Focus, evidenčného čísla G.XXXW., pričom vzhľadom na poznatok o uloženom zákaze činnosti viesť motorové vozidlá bol zastavený hliadkou Obvodného oddelenia Policajného zboru Komárno s volacím znakom Kobalt 351, pri kontrole nevedel predložiť vodičský preukaz, z uvedeného dôvodu hliadka vykonala lustráciu, ktorou zistila, že má rozhodnutím Okresného dopravného inšpektorátu Okresného riaditeľstva Policajného zboru v Komárne zo dňa 7. decembra 2017 pod číslom ORPZ-KN-ODI2-P-860/2017, ktoré nadobudlo právoplatnosť dňa 27. decembra 2017, uložený zákaz činnosti viesť motorové vozidlá na dobu 12 mesiacov,
ATTRIBUTES:
```json
{
  "revokingAuthority": "Okresný dopravný inšpektorát Okresného riaditeľstva Policajného zboru",
  "authorityLocation": "Komárno",
  "revocationDateLegalEffect": "27.12.2017",
  "decisionDate": "07.12.2017",
  "revocationDuration": "12 mesiacov",
  "dateOfOffense": "01.02.2018",
  "timeOfOffense": "17:32",
  "placeOfOffense": "Komárno",
  "placeDetails": "Eötvösova ulica",
  "vehicleModel": "Ford Focus",
  "vehicleType": "car",
  "checkedBy": "Hliadka Obvodného oddelenia Policajného zboru Komárno",
  "typeOfDrivingBan": "viesť motorové vozidlá",
  "typeOfRoad": "urban",
  "reasonForRevocation": "Vedenie motorového vozidla napriek uloženému zákazu činnosti viesť motorové vozidlá",
  "additionalViolations": "Nepredloženie vodičského preukazu pri kontrole"
}
```
EXTRA:
```json
{
  "note": "Evidenčné číslo vozidla bolo G.XXXW., hliadka mala volací znak Kobalt 351 a rozhodnutie bolo vydané pod číslom ORPZ-KN-ODI2-P-860/2017."
}
```
2162837
, ž e  dňa 22.02.2015 v čase o 14.10 hod. po ceste č. I/XX v smere od P. A. na U., viedol osobné motorové vozidlo zn. N. Q EČ: N.-XXX H. a nakoľko prekročil dovolenú rýchlosť jazdy, bol na C. Z. zastavený a kontrolovaný hliadkou OR PZ, ODI Lučenec, pričom uvedeného konania sa dopustil napriek tomu, že trestným rozkazom Okresného súdu v Bratislave 1, sp. zn. 5T/61/2013 zo dňa 10.11.2013, ktorý nadobudol právoplatnosť dňa 26.01.2014, bol uznaný vinným zo spáchania prečinu marenia výkonu úradného rozhodnutia podľa § 348 odsek 1 písmeno d) Trestného zákona a bol mu uložený peňažný trest vo výmere 800€, ako aj trest zákazu činnosti viesť motorové vozidlá akéhokoľvek druhu na dobu 3 rokov,
ATTRIBUTES:
```json
{
  "revokingAuthority": "Okresného súdu v Bratislave 1",
  "authorityLocation": "Bratislave 1",
  "revocationDateLegalEffect": "26.01.2014",
  "decisionDate": "10.11.2013",
  "revocationDuration": "3 rokov",
  "dateOfOffense": "22.02.2015",
  "timeOfOffense": "14:10",
  "placeOfOffense": "anonymized",
  "placeDetails": "po ceste č. I/XX v smere od P. A. na U., na C. Z.",
  "vehicleModel": "anonymized",
  "vehicleType": "car",
  "checkedBy": "hliadkou OR PZ, ODI Lučenec",
  "typeOfDrivingBan": "viesť motorové vozidlá akéhokoľvek druhu",
  "typeOfRoad": "class_I",
  "reasonForRevocation": "marenia výkonu úradného rozhodnutia podľa § 348 odsek 1 písmeno d) Trestného zákona",
  "additionalViolations": "prekročil dovolenú rýchlosť jazdy"
}
```
EXTRA:
```json
{
  "note": "Páchateľovi bol uložený peňažný trest vo výmere 800€."
}
```
2009959
, ž e
dňa 06.02.2018 v čase o 10.08 h. viedol po ul. Duklianskych hrdinov v meste Malacky osobné motorové
vozidlo zn. K. F. combi, ev. č.: MA-XXXDG, kde bol zastavený a kontrolovaný hliadkou ODI Malacky,
pričom vykonanou lustráciou bolo zistené, že vozidlo viedol i napriek tomu, že mu bol rozhodnutím ODI
Bratislava V pod Č.p.: ORP-P-606/BAV-OBCP-2016 z dňa 01.08.2016, právoplatným dňa 30.08.2016,
uložený trest zákazu činnosti viesť motorové vozidlá na dobu 24 mesiacov a trestným rozkazom
Okresného súdu Bratislava V sp. zn. 0T/248/2016 z dňa 25.10.2016, právoplatným dňa 25.10.2016,
uložený trest zákazu činnosti viesť motorové vozidlá na dobu 36 mesiacov, o ktorých vedel,
ATTRIBUTES:
```json
{
  "revokingAuthority": "ODI Bratislava V",
  "authorityLocation": "Bratislava V",
  "revocationDateLegalEffect": "30.08.2016",
  "decisionDate": "01.08.2016",
  "revocationDuration": "24 mesiacov",
  "dateOfOffense": "06.02.2018",
  "timeOfOffense": "10:08",
  "placeOfOffense": "Malacky",
  "placeDetails": "ul. Duklianskych hrdinov",
  "vehicleModel": "anonymized combi",
  "vehicleType": "car",
  "checkedBy": "hliadkou ODI Malacky",
  "typeOfDrivingBan": "viesť motorové vozidlá",
  "typeOfRoad": "urban",
  "reasonForRevocation": "n/a",
  "additionalViolations": "n/a"
}
```
EXTRA:
```json
{
  "note": "Okrem zákazu činnosti uloženého rozhodnutím ODI Bratislava V mu bol uložený aj trest zákazu činnosti viesť motorové vozidlá na dobu 36 mesiacov trestným rozkazom Okresného súdu Bratislava V sp. zn. 0T/248/2016 z dňa 25.10.2016, ktorý nadobudol právoplatnosť v ten istý deň."
}
```
2169234
, ž e  dňa 29.08.2016, v čase o 12:55 hod., viedol osobné motorové vozidlo značky Q. M., D. Č. K.-XXXFM, majiteľom ktorého je F. O., J.. XX.XX.XXXX, Y. G. K., W.. I. U. XXXX/XX, po štátnej ceste I/18, smerom od mesta Prešov k mestu Vranov nad Topľou, kde v obci Čierne nad Topľou bol zastavený a kontrolovaný hliadkou ODI Vranov nad Topľou, pričom pri kontrole bolo zistené, že vozidlo viedol, aj keď mu bol dňa 09.05.2016 rozhodnutím Okresného dopravného inšpektorátu v Prešove, pod číslom Q.-K.-Q.-XXX/ XXXX-K., ktoré nadobudlo právoplatnosť dňa 09.05.2016, uložený zákaz činnosti viesť motorové vozidlá všetkých druhov na dobu 60 mesiacov odo dňa nadobudnutia právoplatnosti rozhodnutia, t. j. od dňa 09.05.2016 do 09.05.2021,
ATTRIBUTES:
```json
{
  "revokingAuthority": "Okresný dopravný inšpektorát",
  "authorityLocation": "Prešov",
  "revocationDateLegalEffect": "09.05.2016",
  "decisionDate": "09.05.2016",
  "revocationDuration": "60 mesiacov",
  "dateOfOffense": "29.08.2016",
  "timeOfOffense": "12:55",
  "placeOfOffense": "Čierne nad Topľou",
  "placeDetails": "smerom od mesta Prešov k mestu Vranov nad Topľou",
  "vehicleModel": "anonymized",
  "vehicleType": "car",
  "checkedBy": "ODI Vranov nad Topľou",
  "typeOfDrivingBan": "viesť motorové vozidlá všetkých druhov",
  "typeOfRoad": "class_I",
  "reasonForRevocation": "riadenie vozidla napriek uloženému zákazu činnosti viesť motorové vozidlá všetkých druhov",
  "additionalViolations": "n/a"
}
```
EXTRA:
```json
{
  "note": "Vozidlo malo evidenčné číslo D. Č. K.-XXXFM a jeho majiteľom je F. O., nar. XX.XX.XXXX, Y. G. K., W.. I. U. XXXX/XX."
}
```
2351172
, že
dňa 08.02.2018 v čase o 15.00 hod. v obci E., H. L. P., okres Dunajská Streda, napriek vedomosti o tom,
že rozhodnutím o priestupku Okresného dopravného inšpektorátu Dunajská Streda zo dňa 20.09.2017
č. X.-M.-X.-XXX/XXXX-S.., ktoré rozhodnutie nadobudlo právoplatnosť dňa 31.10.2017, mu bola okrem
iného uložená sankcia zákazu činnosti viesť motorové vozidlá na dobu 24 mesiacov so započítaním času
od zadržania vodičského preukazu odo dňa 19.05.2017, viedol osobné motorové vozidlo značky Fiat
Brava, evidenčné číslo M. XXXBA, kedy bol zastavený a kontrolovaný hliadkou Obvodného oddelenia
Policajného zboru Dunajská Streda,
ATTRIBUTES:
```json
{
  "revokingAuthority": "Okresný dopravný inšpektorát Dunajská Streda",
  "authorityLocation": "Dunajská Streda",
  "revocationDateLegalEffect": "31.10.2017",
  "decisionDate": "20.09.2017",
  "revocationDuration": "24 mesiacov",
  "dateOfOffense": "08.02.2018",
  "timeOfOffense": "15:00",
  "placeOfOffense": "anonymized",
  "placeDetails": "H. L. P., okres Dunajská Streda",
  "vehicleModel": "Fiat Brava",
  "vehicleType": "car",
  "checkedBy": "hliadka Obvodného oddelenia Policajného zboru Dunajská Streda",
  "typeOfDrivingBan": "zákaz činnosti viesť motorové vozidlá",
  "typeOfRoad": "n/a",
  "reasonForRevocation": "Viedol motorové vozidlo napriek právoplatnému zákazu činnosti viesť motorové vozidlá",
  "additionalViolations": "n/a"
}
```
EXTRA:
```json
{
  "note": "Rozhodnutie o priestupku malo číslo X.-M.-X.-XXX/XXXX-S.. a sankcia zákazu činnosti viesť motorové vozidlá bola uložená so započítaním času od zadržania vodičského preukazu odo dňa 19.05.2017 pre vozidlo s evidenčným číslom M. XXXBA."
}
```
1944171
, že  dňa 15.01.2018 v čase približne o 10:35 hod. viedol po juhovýchodnom obchvate mesta Trnava ako vodič osobné motorové vozidlo značky BMW M135i xDrive, s evidenčným číslom TT210HC, a to napriek tomu, že mu bol trestným rozkazom Okresného súdu Trnava sp. zn. 0T 58/2017 zo dňa 18.03.2017, právoplatným dňa 18.03.2017, uložený trest zákazu činnosti viesť motorové vozidlá akéhokoľvek druhu na dobu 18 mesiacov,
ATTRIBUTES:
```json
{
  "revokingAuthority": "Okresného súdu Trnava",
  "authorityLocation": "Trnava",
  "revocationDateLegalEffect": "18.03.2017",
  "decisionDate": "18.03.2017",
  "revocationDuration": "18 mesiacov",
  "dateOfOffense": "15.01.2018",
  "timeOfOffense": "10:35",
  "placeOfOffense": "Trnava",
  "placeDetails": "juhovýchodnom obchvate",
  "vehicleModel": "BMW M135i xDrive",
  "vehicleType": "car",
  "checkedBy": "n/a",
  "typeOfDrivingBan": "akéhokoľvek druhu",
  "typeOfRoad": "urban",
  "reasonForRevocation": "n/a",
  "additionalViolations": "n/a"
}
```
EXTRA:
```json
{
  "note": "Vozidlo malo evidenčné číslo TT210HC a zákaz činnosti bol uložený trestným rozkazom sp. zn. 0T 58/2017."
}
```
1763003
, že  hoci mu bol rozhodnutím o priestupku Okresného riaditeľstva Policajného zboru Bratislava V, Okresného dopravného inšpektorátu , č.k. : ORP-P-972/BAV-OBCP-2016 zo dňa 16.01.2017, právoplatným dňa 06.02.2017 a vykonateľným dňa 21.02.2017, okrem iného uložený zákaz činnosti viesť motorové vozidlá na dobu 16 /šesťnásť/ mesiacov,  napriek tomu dňa 30.08.2017 v čase okolo 01.20 hod. v meste Senec, na Mierovom námestí viedol osobné motorové vozidlo továrenskej značky Alfa Romeo, Z..Č.. : A. XXX J., kedy bol predpísaným spôsobom zastavený a kontrolovaný hliadkou Okresného riaditeľstva Policajného zboru Senec, Obvodného oddelenia Policajného zboru Senec,
ATTRIBUTES:
```json
{
  "revokingAuthority": "Okresné riaditeľstvo Policajného zboru Bratislava V, Okresné dopravné inšpektorát",
  "authorityLocation": "Bratislava V",
  "revocationDateLegalEffect": "06.02.2017",
  "decisionDate": "16.01.2017",
  "revocationDuration": "16 mesiacov",
  "dateOfOffense": "30.08.2017",
  "timeOfOffense": "01:20",
  "placeOfOffense": "Senec",
  "placeDetails": "Mierové námestie",
  "vehicleModel": "Alfa Romeo",
  "vehicleType": "car",
  "checkedBy": "hliadka Okresného riaditeľstva Policajného zboru Senec, Obvodného oddelenia Policajného zboru Senec",
  "typeOfDrivingBan": "viesť motorové vozidlá",
  "typeOfRoad": "n/a",
  "reasonForRevocation": "n/a",
  "additionalViolations": "n/a"
}
```
EXTRA:
```json
{
  "note": "Rozhodnutie o priestupku Okresného riaditeľstva Policajného zboru Bratislava V malo číslo konania ORP-P-972/BAV-OBCP-2016 a stalo sa vykonateľným dňa 21.02.2017; osobné motorové vozidlo Alfa Romeo malo evidenčné číslo A. XXX J."
}
```
1645649
, ž e : napriek tomu, že mu trestným rozkazom Okresného súdu Prievidza sp.zn. 0T/96/2017 z 2.10.2017, právoplatným 12.10.2017, bol uložený trest zákazu činnosti viesť motorové vozidlá všetkého druhu na dobu 20 mesiacov, 10.1.2018 o 22.08 hod. viedol po ceste I/9 v E.-A. do Prievidze osobné motorové vozidlo M. Y., evidenčné číslo PD XXX EY;
ATTRIBUTES:
```json
{
  "revokingAuthority": "Okresného súdu Prievidza",
  "authorityLocation": "Prievidza",
  "revocationDateLegalEffect": "12.10.2017",
  "decisionDate": "02.10.2017",
  "revocationDuration": "20 mesiacov",
  "dateOfOffense": "10.01.2018",
  "timeOfOffense": "22:08",
  "placeOfOffense": "anonymized",
  "placeDetails": "po ceste I/9 v E.-A. do Prievidze",
  "vehicleModel": "anonymized",
  "vehicleType": "car",
  "checkedBy": "n/a",
  "typeOfDrivingBan": "viesť motorové vozidlá všetkého druhu",
  "typeOfRoad": "class_I",
  "reasonForRevocation": "driving during a ban",
  "additionalViolations": "n/a"
}
```
EXTRA:
```json
{
  "note": "Trest bol uložený trestným rozkazom sp.zn. 0T/96/2017 a vozidlo malo evidenčné číslo PD XXX EY."
}
```
2075892
, ž e
dňa 26.01.2018 v čase o 11:15 hodine v X. po ulici B., v obci B. a následne v obci J., po ceste číslo D.,
pri zubnom stredisku viedol ako vodič osobné motorové vozidlo značky Honda Civic, evidenčné číslo:
X.-XXX B., červenej farby,
hoci v uvedenej dobe mal rozhodnutím Okresného dopravného inšpektorátu X. pod číslom konania H.-
K.-H.-XX/XXXX zo dňa 03.05.2017, právoplatným dňa 18.07.2017 uložený zákaz činnosti viesť motorové
vozidlá na dobu 60 mesiacov, rozhodnutím Okresného dopravného inšpektorátu X. pod číslom konania
H.-K.-H.-XXX/XXXX zo dňa 23.08.2017, právoplatným dňa 11.09.2017 uložený zákaz činnosti viesť
motorové vozidlá na dobu 60 mesiacov a rozhodnutím Okresného dopravného inšpektorátu X. pod

In [86]:
# augment with city size
for key in MARENKY_STRUCTURED:
    placeOfOffense = MARENKY_STRUCTURED[key]["placeOfOffense"]
    MARENKY_STRUCTURED[key]["citySize"] = cities.get(placeOfOffense, "n/a")

In [87]:
df = pd.DataFrame.from_dict(MARENKY_STRUCTURED, orient="index").reset_index()
df.to_csv("marenky_attributes_updated_with_city_size.csv", index=False)
df

,index,revokingAuthority,authorityLocation,revocationDateLegalEffect,decisionDate,revocationDuration,dateOfOffense,timeOfOffense,placeOfOffense,placeDetails,vehicleModel,vehicleType,checkedBy,typeOfDrivingBan,typeOfRoad,reasonForRevocation,additionalViolations,note,sentence,citySize
0,2154941,Okresný súd Senica,Senica,27.10.2014,27.10.2014,12 mesiacov,30.07.2017,08:23,Brodské,na ceste II. triedy č. 425 na hraničnom precho...,anonymized,car,hliadkou OO PZ Brodské,zákaz činnosti viesť motorové vozidlá,class_II,"viedol motorové vozidlo i napriek tomu, že má ...",n/a,Zákaz činnosti viesť motorové vozidlá mu začal...,", ž e dňa 30.07.2017 v čase o 8:23 hod. viedo...",n/a
1,1636460,Okresného súdu Bratislava II,Bratislava II,25.10.2017,25.10.2017,36 mesiacov,22.01.2018,23:10,Stupava,smere zo Zdravotníckej ulice na Hlavnú ulicu,anonymized,car,n/a,akéhokoľvek druhu,urban,"Viedol motorové vozidlo napriek tomu, že mu bo...",n/a,Trestný rozkaz mal číslo 0T/357/2017 a vozidlo...,dňa 22.01.2018 v čase okolo 23.10 h v Stupave ...,12108
2,2162446,Okresného dopravného inšpektorátu Michalovce,Michalovce,28.09.2017,06.09.2017,12 mesiacov,30.01.2018,14:30,Žbince,v smere od základnej školy smerom k rómskej osade,anonymized,car,policajnou hliadkou,viesť motorové vozidlo,class_III,priestupok proti bezpečnosti a plynulosti cest...,nesvietili stretávacie svetlá,Rozhodnutie Okresného dopravného inšpektorátu ...,"aj napriek tomu, že rozhodnutím Okresného dopr...",n/a
3,1638701,Okresný súd Malacky,Malacky,19.05.2017,19.05.2017,15 mesiacov,25.01.2018,02:50,Stupava,Železničná ulica,anonymized,car,n/a,viesť motorové vozidlá akéhokoľvek druhu,urban,Viedol motorové vozidlo napriek právoplatnému ...,n/a,Vozidlo malo e.č.: MA-XXX DB a zákaz činnosti ...,dňa 25.01.2018 v čase okolo 02.50 h v Stupave ...,12108
4,2221001,Okresný súd Námestovo,Námestovo,12.03.2016,25.02.2016,40 mesiacov,19.01.2018,13:33,Trstená,na ulici Oravickej pri rodinnom dome číslo XXX/XX,KUBOTA,other,hliadka Obvodného oddelenia PZ Trstená,všetky motorové vozidlá,urban,Šoférovanie počas zákazu činnosti,n/a,"Ďalšie informácie v texte, ktoré neboli pokryt...","i napriek tomu, že trestným rozkazom Okresného...",7360
5,1641467,Okresný dopravný inšpektorát Okresného riadite...,Komárno,27.12.2017,07.12.2017,12 mesiacov,01.02.2018,17:32,Komárno,Eötvösova ulica,Ford Focus,car,Hliadka Obvodného oddelenia Policajného zboru ...,viesť motorové vozidlá,urban,Vedenie motorového vozidla napriek uloženému z...,Nepredloženie vodičského preukazu pri kontrole,"Evidenčné číslo vozidla bolo G.XXXW., hliadka ...",", že dňa 1. februára 2018 v čase o 17.32 hodin...",33751
6,2162837,Okresného súdu v Bratislave 1,Bratislave 1,26.01.2014,10.11.2013,3 rokov,22.02.2015,14:10,anonymized,"po ceste č. I/XX v smere od P. A. na U., na C. Z.",anonymized,car,"hliadkou OR PZ, ODI Lučenec",viesť motorové vozidlá akéhokoľvek druhu,class_I,marenia výkonu úradného rozhodnutia podľa § 34...,prekročil dovolenú rýchlosť jazdy,Páchateľovi bol uložený peňažný trest vo výmer...,", ž e dňa 22.02.2015 v čase o 14.10 hod. po c...",n/a
7,2009959,ODI Bratislava V,Bratislava V,30.08.2016,01.08.2016,24 mesiacov,06.02.2018,10:08,Malacky,ul. Duklianskych hrdinov,anonymized combi,car,hliadkou ODI Malacky,viesť motorové vozidlá,urban,n/a,n/a,Okrem zákazu činnosti uloženého rozhodnutím OD...,", ž e\ndňa 06.02.2018 v čase o 10.08 h. viedol...",17467
8,2169234,Okresný dopravný inšpektorát,Prešov,09.05.2016,09.05.2016,60 mesiacov,29.08.2016,12:55,Čierne nad Topľou,smerom od mesta Prešov k mestu Vranov nad Topľou,anonymized,car,ODI Vranov nad Topľou,viesť motorové vozidlá všetkých druhov,class_I,riadenie vozidla napriek uloženému zákazu činn...,n/a,Vozidlo malo evidenčné číslo D. Č. K.-XXXFM a ...,", ž e dňa 29.08.2016, v čase o 12:55 hod., vi...",n/a
9,2351172,Okresný dopravný inšpektorát Dunajská Streda,Dunajská Streda,31.10.2017,20.09.2017,24 mesiacov,08.02.2018,15:00,anonymized,"H. L. P., okres Dunajská Streda",Fiat Brava,car,hliadka Obvodného oddelenia Policajného zboru ...,zákaz činnosti viesť motorové vozidlá,n/a,Viedol motorové vozidlo napriek právoplatnému ...,n/a,Rozhodnutie o priestupku malo číslo X.-M.-X.-X...,", že\ndňa 08.02.2018 v čase o 15.00 hod. v obc...",n/a
10,1944171,Okresného súdu Trnava,Trnava,18.03.2017,18.03.2017,18 mesiacov,15.01.2018,10:35,Trnava,juhovýchodnom obchvate,BMW M135i xDrive,car,n/a,akéhokoľvek druhu,urban,n/a,n/a,Vozidlo malo evidenčné číslo TT210HC a zákaz č...,", že dňa 15.01.2018 v čase približne o 10:35 ...",65033
11,1763003,Okresné riaditeľstvo Policajného zboru Bratisl...,Bratislava V,06.02.2017,16.01.2017,16 mesiacov,30.08.2017,01:20,Senec,Mierové námestie,Alfa Romeo,car,hliadka Okresného riaditeľstva Policajného zbo...,viesť motorové vozidlá,n/a,n/a,n/a,Rozhodnutie o priestupku Okresného riaditeľstv...,", že hoci mu bol rozhodnutím o priestupku Okr...",19963
12,1645649,Okresného súdu Prievidza,Prievidza,12.10.2017,02.10.2017,20 mesiacov,10.01.2018,22:08,anonymized,po ceste I/9 v E.-A. do Prievidze,anonymized,car,n/a,viesť motorové vozidlá všetkého druhu,class_I,driving during a ban,n/a,Trest bol uložený trestným rozkazom sp.zn. 0T/...,", ž e : napriek tomu, že mu trestným rozkazom ...",n/a
13,2075892,Okresný dopravný inšpektorát,X.,07.11.2017,02.10.2017,24 mesiacov,26.01.2018,11:15,anonymized,"po ulici B., v obci B. a následne v obci J., p...",Honda Civic,car,n/a,všetky motorové vozidlá,n/a,riadenie motorového vozidla počas zákazu činno...,n/a,Vozidlo Honda Civic bolo červenej farby a okre...,", ž e\ndňa 26.01.2018 v čase o 11:15 hodine v ...",n/a
14,2116836,Okresného súdu Michalovce,Michalovce,27.07.2016,12.07.2016,18 mesiacov,10.12.2016,17:15,Falkušovce,pri potravinách COOP Jednota,anonymized,car,OO PZ Trhovište,viesť motorové vozidlá všetkých druhov,urban,n/a,n/a,Rozhodnutie Okresného súdu Michalovce malo spi...,dňa 10.12.2016 o 17.15 hod. viedol v obci Falk...,n/a
15,2106856,n/a,n/a,n/a,n/a,n/a,07.02.2018,05:12,outside town/city limits,"okres Levice, medzi obcami Tekovský Hrádok a Š...",anonymized,truck,Okresný dopravný inšpektorát Okresného riaditľ...,všetky druhy vozidiel,other,viedol motorové vozidlo napriek zákazu činnosti,n/a,"Vlastníkom vozidla s EČ: D je N. T. G., XXXX A...",dňa 07.02.2018 v čase o 05.12 h medzi obcami T...,n/a
16,2343658,Okresný súd W.,W.,24.02.2017,25.01.2017,36 mesiacov,26.07.2017,09:10,W.,ulici M. J.,anonymized,car,hliadkou Y. F. J. W.,všetkých druhov,urban,n/a,prekročenie rýchlosti,Trestný rozkaz Okresného súdu W. mal spisovú z...,dňa 26.7.2017 v čase o 09.10 hod. ako vodič vi...,n/a
17,1731943,"Okresné riaditeľstvo PZ, Okresný dopravný inšp...",Prešov,05.05.2015,05.05.2015,16 mesiacov,11.05.2015,12:10,Prešov,n/a,Volkswagen Bora,car,n/a,viesť motorové vozidlá,n/a,n/a,n/a,V texte sa nachádza evidenčné číslo vozidla T....,"dňa 11.5.2015 v čase o 12.10 hod. v Prešove, v...",88464
18,1741063,Okresný súd Bratislava V,Bratislava,31.10.2017,30.10.2017,2 roky,30.01.2018,20:30,Bratislava,po Botanickej ulici a následne prešiel na Prib...,Rover 200,car,policajnou hliadkou,motorové vozidlá,urban,n/a,viedol motorové vozidlo napriek zákazu činnosti,Vodičovi boli predtým uložené zákazy činnosti ...,", ž e dňa 30. 01. 2018 o 20.30 h v Bratislav...",437725
19,1953452,Okresný súd Komárno,Komárno,19.06.2017,19.06.2017,18 mesiacov,09.02.2018,08:40,anonymized,za obcou R. P. v smere na obec Okoličná na Ost...,Fiat Punto,car,hliadkou OO PZ Zemianska Olča,všetky motorové vozidlá,n/a,n/a,vedenie vozidla bez používania predpísaného os...,Vozidlo bolo červenej farby s evidenčným číslo...,dňa 9. februára 2018 v čase o 08.40 hod. za ob...,n/a
20,1976863,Okresný súd Prievidza,Prievidza,16.07.2016,04.07.2016,36 mesiacov,16.03.2017,08:51,Handlová,Ulici Mostná,anonymized,car,n/a,všetkého druhu,urban,n/a,n/a,Rozhodnutie súdu bolo trestným rozkazom sp. zn...,": i napriek tomu, že jej bol trestným rozkazo...",16890
21,2293789,"Okresné riaditeľstvo PZ Michalovce, Okresný do...",Michalovce,02.09.2015,02.09.2015,36 mesiacov,27.10.2017,22:40,Bratislava,Stará Vajnorská ulica,Ford Escort,car,hliadka Pohotovostnej motorizovanej jednotky K...,viesť motorové vozidlá,urban,n/a,n/a,Motorové vozidlo zn. Ford Escort bolo zelenej ...,", že v čase okolo 22.40 hod. dňa 27.,10. 2017...",437725
22,1750947,"Okresné riaditeľstvo PZ Rožňava, Okresný dopra...",Rožňava,07.08.2017,07.08.2017,8 mesiacov,17.09.2017,19:10,anonymized,na F. J.,Mercedes Benz Sprinter,van,"hliadka Okresného riaditeľstva PZ Revúca, Obvo...",viesť motorové vozidlo,urban,spáchanie priestupku podľa § 22 ods. 1 písm. e...,n/a,Podľa § 14 ods. 2 zákona č. 372/1990 Zb. o pri...,dňa 17. septembra 2017 o 19.10 h ako vodič v m...,n/a
23,1955340,Okresného súdu Bratislava II,Bratislava II,XX.XX.XXXX,XX.XX.XXXX,X roky,XX.XX.XXXX,XX:XX,anonymized,z W. ulice na T. ulicu,anonymized,car,n/a,viesť motorové vozidlá akéhokoľvek druhu,urban,n/a,n/a,Trestný rozkaz bol vydaný pod sp. zn. XT/XXX/X...,XX.XX.XXXX v čase asi o XX:XX hod. viedol v X....,n/a
24,2147353,Okresného súdu Košice II,Košice,24.11.2015,24.11.2015,2 roky,05.09.2017,16:36,anonymized,po ceste 1/20 Q. E. O.,anonymized,car,hliadkou Diaľničného oddelenie PZ Prešov,viesť všetky druhy motorových vozidiel,class_I,marenia výkonu úradného rozhodnutia podľa § 34...,prekročil maximálnu povolenú rýchlosť v obci o...,Zákaz činnosti bol uložený trestným rozkazom O...,z prečinu marenia výkonu úradného rozhodnutia ...,n/a
25,1764659,"[Okresný súd Košice I, Okresný dopravný inšpek...","[Košice I, Trebišov]","[27.03.2013, 30.09.2013]","[30.03.2012, 14.01.2013]","[5 rokov, 60 mesiacov]",15.01.2018,01:40,anonymized,"ul. U., pri pohostinstve „Bindas“",Opel Astra Caravan,car,policajnou hliadkou OO PZ Michaľany,všetky druhy motorových vozidiel,urban,Vedenie motorového vozidla napriek uloženému z...,Vedenie vozidla bez príslušného vodičského opr...,Evidenčné číslo vozidla bolo C. a rozhodnutia ...,", ž e dňa 15.1.2018 okolo 01.40 hod. viedol b...",n/a
26,2207170,n/a,n/a,n/a,n/a,n/a,16.02.2016,01:15,H.,"okres B. H., F. republika",Audi A4 Avant,car,n/a,n/a,n/a,n/a,n/a,Dňa 09.05.2016 na hlavnom pojednávaní na Okres...,dňa 09.05.2016 v presne nezistenom čase na hla...,n/a
27,1993413,Okresný súd v Čadci,Čadca,08.03.2017,10.01.2017,18 mesiacov,30.09.2017,19:20,anonymized,po ulici D. smerom na ulici B.,anonymized,car,n/a,viesť motorové vozidlá,urban,Riadenie motorového vozidla počas zákazu činnosti,n/a,V texte je uvedené evidenčné číslo vozidla K. ...,dňa 30.9.2017 v čase o 19:20 hod. viedol po ul...,n/a
28,2395454,"Okresným riaditeľstvom PZ, Okresným dopravným ...",Michalovce,16.02.2017,12.12.2016,24 mesiacov,13.02.2018,18:55,Falkušovce,"v obci Falkušovce, v smere na obec Malčice",Audi A4,car,OO PZ Trhovište,motorové vozidlá,class_II,n/a,n/a,Rozhodnutím o priestupku mu bola uložená pokut...,", ž e dňa 13.2.2018 čase o 18.55 hod. viedol ...",n/a
29,1625732,Okresný dopravný inšpektorát,Pezinok,15.04.2014,24.03.2014,36 mesiacov,25.02.2017,22:57,Bratislava,"Lamač, po lamačskej ceste smerom na ulicu Jank...",Cooper Mini One,car,hliadkou Obvodného oddelenia PZ Dúbravka,viesť motorové vozidlá,n/a,n/a,n/a,Okrem toho bol vodičovi trestným rozkazom Okre...,",\nž e\ndňa 25.02.2017 v čase o 22:57 h v Brat...",437725
30,2366676,Okresného dopravného inšpektorátu Okresného ri...,Dunajská Streda,01.03.2017,01.03.2017,16 mesiacov,14.02.2018,00:05,Lehnice,"na miestnej komunikácii v obci Lehnice, časť M...",Škoda Octavia,car,n/a,motorové vozidlá akéhokoľvek druhu,urban,Vedenie motorového vozidla počas zákazu činnos...,n/a,Viedol osobné motorové vozidlo farby čierna me...,", že dňa 14.2.2018 v čase o 00.05 hodine na m...",n/a
31,1649136,Okresného dopravného inšpektorátu,G. J.,07.11.2017,18.10.2017,24 mesiacov,31.12.2017,23:50,anonymized,na ulici Š.,Škoda Felicia,car,n/a,zákazu činnosti viesť motorové vozidlá,n/a,n/a,n/a,Obvinenému bol predtým uložený zákaz činnosti ...,dňa 31.12.2017 v čase okolo 23:50 hod. v obci ...,n/a
32,2064848,Okresný dopravný inšpektorát,Trenčín,20.01.2016,n/a,24 mesiacov,27.09.2016,09:00,anonymized,časť D. od ulice Y. po ulici Z.,Škoda Felicia,car,n/a,každého druhu,n/a,n/a,n/a,Rozhodnutie Okresného dopravného inšpektorátu ...,dňa 27.09.2016 o 09.00 hod. v obci U. časť D. ...,n/a
33,1622218,Okresný dopravný inšpektorát OR PZ,Lučenec,21.11.2017,21.11.2017,24 mesiacov,14.01.2018,10:15,n/a,K.M.,Fiat Brava,car,hliadkou OO PZ G.,zákaz činnosti viesť motorové vozidlá,n/a,n/a,nepredložil vodičský preukaz,Vozidlo malo evidenčné číslo E. a rozhodnutie ...,", ž e\n14.01.2018 viedol po K.M. ako vodič oso...",n/a
34,1580871,Okresným dopravným inšpektorátom v K.,K.,24.03.2015,24.03.2015,48 mesiacov,13.12.2017,15:40,K.,na ulici G.,Fiat Stilo,car,n/a,viesť motorové vozidlá každého druhu,urban,n/a,n/a,Motorové vozidlo značky Fiat Stilo bolo žltej ...,"dňa 13.12.2017 v čase o 15,40 hod. v meste K. ...",n/a
35,2383728,Okresný dopravný inšpektorát - Oddelenie bezpe...,Galanta,18.10.2017,02.08.2017,6 mesiacov,11.02.2018,00:59,Bratislava,zo Železničnej ulice na Stavbársku ulicu,anonymized,car,n/a,všetky motorové vozidlá,n/a,n/a,n/a,Motorové vozidlo bolo striebornej farby s EČV:...,dňa 11.02.2018 v čase okolo 00:59 hod. v Brati...,437725
36,1663801,"ORPZ, ODI Ružomberok; ORPZ, ODI Košice; Okresn...",Ružomberok; Košice; Košice; Košice,24.07.2017; 08.08.2017; 08.08.2017; 16.11.2017,06.06.2017; 08.08.2017; 08.08.2017; 16.11.2017,4 roky; 2 roky; 3 roky; 3 roky,02.02.2018,23:35,Košice,ulica Kuzmányho,Mitsubishi Galant,car,policajná hliadka,všetky druhy motorových vozidiel,urban,Vedenie motorového vozidla napriek viacerým pl...,n/a,V texte je ďalej uvedené evidenčné číslo vozid...,-menovaný dňa 02.02.2018 v čase o 23.35 hod. v...,238593
37,1834613,"Okresné riaditeľstvo PZ Senec, Okresným doprav...",Senec,14.08.2017,25.07.2017,12 mesiacov,03.02.2018,15:45,Senec,Pezinskej ulici,KIA Cee´d,car,hliadkou Obvodného oddelenia PZ Senec,zákaz činnosti viesť motorové vozidlá,urban,n/a,n/a,"Farba vozidla bola strieborná metalíza, jeho e...",", že dňa 03.02.2018 v čase o 15.45 hod. v mes...",19963
38,1871682,Okresný súd Brezno,Brezno,22.10.2014,22.10.2014,1 rok,23.01.2018,15:45,Brezno,"na ceste č. I/66, časť Predné Halny",Škoda Octavia,car,n/a,zákazu činnosti vedenia motorových vozidiel,class_I,n/a,n/a,Páchateľ bol obvinený z prečinu marenia výkonu...,z prečinu marenia výkonu úradného rozhodnutia ...,20889
39,1658750,Okresného súdu Bratislava III,Bratislava III,06.02.2017,06.02.2017,4 roky,06.08.2017,14:10,Most pri Bratislave,po Bratislavskej ulici,Peugeot 306,car,hliadkou OO PZ Dunajská Lužná,všetkého druhu,urban,riadenie motorového vozidla napriek zákazu čin...,n/a,"Osobné motorové vozidlo bolo modrej metalízy, ...",dňa 06.08.2017 v čase o 14.10 hod. v obci Most...,n/a
40,1626252,"OR PZ, ODI",Lučenec,08.11.2017,08.11.2017,10 mesiacov,16.01.2018,22:28,Lovinobaňa,pred budovou Obecného úradu Lovinobaňa,Volvo V 50,car,hliadka OO PZ v Lovinobani,viesť motorové vozidlá,n/a,Vedenie vozidla napriek zákazu činnosti,n/a,V texte sa uvádza evidenčné číslo vozidla Q. a...,", ž e dňa 16.01.2018 viedol v obci Lovinobaňa...",n/a
41,1835990,n/a,n/a,04.12.2015,n/a,60 mesiacov,22.01.2018,07:40,Rakytovce,po ceste s označením III/2415 v obci Rakytovce...,Chrysler Grand Voyager,car,hliadkou Okresného dopravného inšpektorátu Ban...,všetky motorové vozidlá,class_III,spáchanie priestupku podľa § 22 odsek 1 písmen...,nepredložil žiadne doklady,Za spáchanie priestupku mu bola uložená pokuta...,dňa 22.01.2018 v čase o 07.40 hodine ako vodič...,n/a
42,2215658,Okresného riaditeľstva Policajného zboru Žiar ...,Žiar nad Hronom,04.10.2016,04.10.2016,20 mesiacov,21.10.2017,22:30,Župkov,po miestnej komunikácii v smere do obce Horné ...,Opel Tigra,car,hliadkou Obvodného oddelenia Policajného zboru...,viesť motorové vozidlá,urban,porušenie zákazu viesť motorové vozidlá,n/a,V texte sa nachádzajú aj informácie o evidenčn...,dňa 21.10.2017 v čase o 22.30 h viedla osobné ...,n/a
43,1631868,Okresný súd v Prievidzi; Krajský súd Trenčín,Prievidza; Trenčín,09.02.2017,XX.X.XXXX; X.X.XXXX,8 mesiacov a 25 dní,06.04.2017,10:40,outside town/city limits,"po ceste I/9 v úseku cesty zvanom „Banská“, ok...",anonymized,car,n/a,všetky motorové vozidlá,class_I,Vedenie motorového vozidla počas platnosti zák...,n/a,Text tiež spomína spisovú značku uznesenia Okr...,"i napriek tomu, že mu bolo uznesením Okresného...",n/a
44,1632883,Okresný dopravný inšpektorát Malacky,Malacky,06.10.2017,06.10.2017,12 mesiacov,22.01.2018,09:40,Malacky,ulici Duklianskych hrdinov,anonymized,car,n/a,viesť motorové vozidlá,urban,Vedenie motorového vozidla počas zákazu činnosti,n/a,Vozidlo malo červenú farbu a evidenčné číslo M...,dňa 22.01.2018 v čase okolo 09.40 h v Malackác...,17467
45,2183269,Okresný súd Bratislava II,Bratislava,14.01.2018,14.01.2018,18 mesiacov,02.02.2018,23:10,Štvrtok na Ostrove,"okres Dunajská Streda, smerom na mesto Bratisl...",Mazda 323,car,hliadkou Obvodného oddelenia Policajného zboru...,viesť motorové vozidlá,class_II,porušenie zákazu činnosti viesť motorové vozidlá,n/a,Viedol osobné motorové vozidlo s evidenčným čí...,", že\ndňa 2.2.2018 v čase o 23.10 hod. v obci ...",n/a
46,2399622,Okresný dopravný inšpektorát Okresného riadite...,Skalica,06.11.2015,06.11.2015,18 mesiacov,29.12.2016 - 09.01.2017,n/a,n/a,po cestách v okrese Skalica,Hyundai i20,car,n/a,viesť motorové vozidlá,n/a,Vedenie vozidla napriek uloženému zákazu činno...,n/a,"Menovaný viedol vozidlá, ktorých vlastníkom je...","v dňoch 29.12.2016, 30.12.2016, 31.12.2016, 02...",n/a
47,2019897,ODI Malacky,Malacky,10.01.2018,10.01.2018,6 mesiacov,07.02.2018,21:05,Malacky,ul. 1. mája,anonymized,bus,OO PZ Malacky,viesť motorové vozidlá,urban,jazda napriek zákazu činnosti,n/a,"Evidenčné číslo vozidla bolo MA-XXXDF, číslo r...",", ž e\ndňa 07.02.2018 v čase o 21.05 h. viedol...",17467

## Drug-impaired driving

In [7]:
POD_VLIVEM_STRUCTURED = {}

In [8]:
def extract_drugs(pod_vlivem):
    print(pod_vlivem["judgement_slt_id"])
    print(pod_vlivem["judgement_factual_sentence"])
    chat = client.chats.create(model="gemini-2.5-flash", config=types.GenerateContentConfig(system_instruction="""You extract values for attributes from text. The texts are the factual statements in court verdicts. Return only information from the text, never make stuff up. If the value for attribute is not provided, return value 'n/a'. The date format id DD.MM.YYYY.  The time format is HH:MM. Decimal number are rounded to two digits after the decimal point: #.##. Format your output as JSON. The values mut be in the original language - Slovak. Extract the follwing attributes:
            substanceUsed [Drug or substance detected]
            substanceUsedType [Type of the substance]
            amountUsed [The amount of drug or substance detected]
            measuringMethod [Type of measurement taken]
            measuringTime [Time of measurement]
            measuringDevice [Measuring device used for testing]
            refusedTesting [True if the offender refused to take a blood test, False otherwise]
            dateOfOffense [Date when the offense occurred]
            timeOfOffense [Time when the offense occurred]
            placeOfOffense [A name of the city/town where the offense occurred]
            placeDetails [Details about where the offense occurred]
            vehicleModel [Vehicle brand and model involved in the offense, e.g Škoda Octavia, or "anonymized" if only capital letters are provided]
            vehicleType [Type of vehicle involved in the offense]
            checkedBy [Who conducted the inspection or check]
            typeOfRoad [Type of road where the offense occurred]
            reasonForCheck [Reason why the inspection was carried out]
            reasonForCheckCategory [Reason why the inspection was carried out]
            licenseStatus [Validity status of the driver's linense]
            lawBroken [A reference to a law that was broken by the offense]
            
            The substanceUsed is coded as follows:
            alcohol
            cannabis
            methamphetamine
            amphetamine       
            cocaine
            mdma
            hashish    
            morphine
            barbiturate 
            benzodiazepine
            methadon 
            heroin
            other

            where ethanol refers to alcohol as welll

            The amountUsed is composed of a number and a unit of measurement, e.g. 0.75 mg/l, 50 ng/ml, 0.70 g/kg

            The substanceUsedType is coded as follows:
            stimulants
            sedatives
            hallucinogens

            where sedatives refer to sedatives or depressants.

            The measuringMethod is coded as follows:
            breath
            blood
            urine
            other
            n/a

            If there are multiple measurements of the same substance, list all of them separated by semicolon, e.g. amountUsed: 0.75 mg/l; 0.5 mg/l, measuringMethod: blood; blood, measuringTime: 22:34; 22:42. When only one type of substance was used, this only applies to attributes amountUsed, measuringMethod, measuringTime whereas substanceUsed has only one value.  However, if there is a use of diffeent substances, then the attributes substanceUsed and substanceUsedType also have multiple values separated by semicolon, e.g. substanceUsed: alcohol; cannabis, amountUsed: 45 ng/l; 22 ng/l. Do not report alcohol values in ‰.

            The placeOfOffense is coded as follows:
            [name of the town/city in Slovak]
            outside town/city limits (if offence occurs outside of any municipality)
            anonymized (e.g. v obci A.B.)
            n/a (if the information in not provided)

            The vehicleType is coded as follows:
            car
            van
            truck
            bus
            motorcycle
            other
            n/a

            The typeOfRoad is coded as follows:
            urban
            motorway
            class_I
            class_II
            other
            n/a (if the information in not provided)

            reasonForCheckCategory is coded as follows:
            traffic_accident
            speeding
            traffic_violation
            suspected_intoxication
            traffic_check
            other
            n/a

            The licenseStatus is coded as follows:
            valid (valid license plate)
            banned (driving despite a ban was imposed or license was taken away)
            none (license never issued, driving without driver's license)
            n/a (license validity not mentioned)
  
"""),
       )
    
    response = chat.send_message(pod_vlivem["judgement_factual_sentence"])
    POD_VLIVEM_STRUCTURED[pod_vlivem["judgement_slt_id"]] = get_json(response.text)
    
    print(f"ATTRIBUTES:\n{response.text}")
      
    response = chat.send_message("What other information was there in the statenent but is not covered by the attributes? Write one sentence containing the extra information. Output a json with one atttribute: 'note' wherethe value is the sentence with extra information. Only output information from the original text. The sentence mut be in the original language - Slovak.")
    POD_VLIVEM_STRUCTURED[pod_vlivem["judgement_slt_id"]]["note"] = get_json(response.text)["note"]
    POD_VLIVEM_STRUCTURED[pod_vlivem["judgement_slt_id"]]["sentence"] = pod_vlivem["judgement_factual_sentence"]
   
    
    print(f"EXTRA:\n{response.text}")

In [ ]:
import time
for i in range(len(pod_vlivem)):     
    pod_vlivem_i = pod_vlivem.iloc[i]
    print(i)
    print(pod_vlivem_i)
    try:
        extract_drugs(pod_vlivem_i)
    except Exception as e:
        time.sleep(30)
        print("Another attempt...")
        extract_drugs(pod_vlivem_i)

## Enrichment with external data

In [15]:
cities = {
  "Bratislava": 437725,
  "Košice": 238593,
  "Prešov": 88464,
  "Žilina": 80727,
  "Banská Bystrica": 78084,
  "Nitra": 76533,
  "Trnava": 65033,
  "Trenčín": 55383,
  "Martin": 54168,
  "Poprad": 51235,
  "Prievidza": 45634,
  "Zvolen": 42167,
  "Považská Bystrica": 39271,
  "Michalovce": 38776,
  "Nové Zámky": 37512,
  "Spišská Nová Ves": 37007,
  "Komárno": 33751,
  "Humenné": 32834,
  "Levice": 32735,
  "Bardejov": 32293,
  "Liptovský Mikuláš": 31000,
  "Lučenec": 27739,
  "Piešťany": 27336,
  "Ružomberok": 26558,
  "Topoľčany": 24785,
  "Trebišov": 24649,
  "Čadca": 23941,
  "Rimavská Sobota": 23751,
  "Dubnica nad Váhom": 23550,
  "Pezinok": 23034,
  "Dunajská Streda": 22684,
  "Partizánske": 22269,
  "Vranov nad Topľou": 22245,
  "Šaľa": 21689,
  "Hlohovec": 21301,
  "Brezno": 20889,
  "Snina": 20289,
  "Senica": 20289,
  "Nové Mesto nad Váhom": 20071,
  "Senec": 19963,
  "Rožňava": 19045,
  "Žiar nad Hronom": 18852,
  "Dolný Kubín": 18665,
  "Bánovce nad Bebravou": 17750,
  "Púchov": 17561,
  "Malacky": 17467,
  "Handlová": 16890,
  "Kežmarok": 16346,
  "Stará Ľubovňa": 16327,
  "Sereď": 15444,
  "Skalica": 15022,
  "Galanta": 14990,
  "Kysucké Nové Mesto": 14953,
  "Levoča": 14722,
  "Detva": 14545,
  "Šamorín": 13350,
  "Sabinov": 12700,
  "Stupava": 12108,
  "Revúca": 11949,
  "Veľký Krtíš": 11755,
  "Myjava": 11514,
  "Zlaté Moravce": 11375,
  "Bytča": 11363,
  "Moldava nad Bodvou": 11307,
  "Holíč": 11156,
  "Nová Dubnica": 11040,
  "Svidník": 10752,
  "Kolárovo": 10586,
  "Fiľakovo": 10568,
  "Stropkov": 10438,
  "Štúrovo": 10186,
  "Banská Štiavnica": 10004,
  "Šurany": 9659,
  "Tvrdošín": 9201,
  "Modra": 9046,
  "Veľké Kapušany": 8862,
  "Stará Turá": 8764,
  "Krompachy": 8684,
  "Veľký Meder": 8612,
  "Vráble": 8551,
  "Sečovce": 8542,
  "Svit": 7923,
  "Krupina": 7912,
  "Námestovo": 7784,
  "Vrútky": 7748,
  "Turzovka": 7515,
  "Kráľovský Chlmec": 7426,
  "Hriňová": 7415,
  "Hnúšťa": 7411,
  "Liptovský Hrádok": 7397,
  "Hurbanovo": 7397,
  "Trstená": 7360,
  "Nová Baňa": 7314,
  "Šahy": 7219,
  "Tornaľa": 7114,
  "Krásno nad Kysucou": 6799,
  "Želiezovce": 6746,
  "Spišská Belá": 6733,
  "Lipany": 6542,
  "Medzilaborce": 6531,
  "Veľký Šariš": 6426,
  "Nemšová": 6414,
  "Sobrance": 6346,
  "Turčianske Teplice": 6330,
  "Žarnovica": 6170,
  "Gelnica": 6047,
  "Vrbové": 5907,
  "Rajec": 5787,
  "Svätý Jur": 5724,
  "Dobšiná": 5685,
  "Poltár": 5584,
  "Gabčíkovo": 5473,
  "Ilava": 5464,
  "Kremnica": 5258,
  "Sládkovičovo": 5209,
  "Gbely": 5073,
  "Nesvady": 5049,
  "Bojnice": 4992,
  "Šaštín-Stráže": 4965,
  "Sliač": 4959,
  "Brezová pod Bradlom": 4768,
  "Medzev": 4482,
  "Turany": 4278,
  "Strážske": 4250,
  "Nováky": 4203,
  "Trenčianske Teplice": 4162,
  "Leopoldov": 4097,
  "Giraltovce": 4089,
  "Tisovec": 4087,
  "Vysoké Tatry": 4009,
  "Spišské Podhradie": 3985,
  "Hanušovce nad Topľou": 3782,
  "Čierna nad Tisou": 3619,
  "Tlmače": 3520,
  "Spišské Vlachy": 3459,
  "Jelšava": 3289,
  "Podolínec": 3155,
  "Rajecké Teplice": 3023,
  "Spišská Stará Ves": 2230,
  "Modrý Kameň": 1624,
  "Dudince": 1395
}

In [443]:
for key in POD_VLIVEM_STRUCTURED:
    placeOfOffense = POD_VLIVEM_STRUCTURED[key]["placeOfOffense"]
    POD_VLIVEM_STRUCTURED[key]["citySize"] = cities.get(placeOfOffense, "n/a")

In [444]:
import re

def average_measurements(measure_str: str) -> str:
    # Handle NaN or None
    if pd.isna(measure_str):
        return measure_str
    
    # If multiple values separated by semicolon

    parts = [p.strip() for p in str(measure_str).split(";")]
    
    values = []
    units = []
    
    for part in parts:
        match = re.match(r"([\d.]+)\s*([a-zA-Zµ/]+)", part)
        if not match:
            return measure_str  # if parsing fails, return original
        value, unit = match.groups()
        unit = unit.replace("L", "l").replace("liter", "l")
        values.append(float(value))
        units.append(unit)
    
    # Check if all units are identical
    if len(set(units)) == 1:
        avg = sum(values) / len(values)
        return f"{avg:.2f} {units[0]}"
    else:
        return measure_str
    
    
    # If not multiple values, just return original
    return measure_str

In [445]:
for key in POD_VLIVEM_STRUCTURED:
    amountUsed = POD_VLIVEM_STRUCTURED[key]["amountUsed"]
    substanceUsed = POD_VLIVEM_STRUCTURED[key]["substanceUsed"]
    if len(set(substanceUsed.split(";"))) == 1:
        amount_with_unit = average_measurements(amountUsed)
        #print(f"{substanceUsed}: {amount_with_unit}")
        parts = amount_with_unit.split(" ")

        if len(parts) == 2:
            try:
                amount = float(parts[0])
            except:
                print(f"Could not process {amountUsed}")
                POD_VLIVEM_STRUCTURED[key]["avgAmountUsed"] = "n/a"      
                POD_VLIVEM_STRUCTURED[key]["avgAmountUsedUnit"] = "n/a"         
                parts_units = parts[1].split("/")
                
            if "alcohol" in substanceUsed and parts[0] == "ng/l":
                print("will divide")
                POD_VLIVEM_STRUCTURED[key]["avgAmountUsed"] = amount/1000
                POD_VLIVEM_STRUCTURED[key]["avgAmountUsedUnit"] = "mg/l"         
            elif "alcohol" not in substanceUsed and parts[1] == "µg/ml":
                POD_VLIVEM_STRUCTURED[key]["avgAmountUsed"] = amount * 1000
                POD_VLIVEM_STRUCTURED[key]["avgAmountUsedUnit"] = "ng/ml"         
            elif  "alcohol" in substanceUsed and parts[1] == "mg/l" or "alcohol" not in substanceUsed and parts[1] == "ng/ml":
                POD_VLIVEM_STRUCTURED[key]["avgAmountUsed"] = amount
                POD_VLIVEM_STRUCTURED[key]["avgAmountUsedUnit"] = parts[1]
            elif parts[1] not in [ "ng/l",  "mg/l",  "ng/ml",  "mg/ml", "µg/ml" ]:
                print( parts[1])
        else:
            POD_VLIVEM_STRUCTURED[key]["avgAmountUsed"] = "n/a"
            POD_VLIVEM_STRUCTURED[key]["avgAmountUsedUnit"] = "n/a"         
    else:
        POD_VLIVEM_STRUCTURED[key]["avgAmountUsed"] = "n/a"
        POD_VLIVEM_STRUCTURED[key]["avgAmountUsedUnit"] = "n/a"

Mg/l
Could not process X.XX mg/l

In [448]:
import numpy as np
df_pod_vlivem = pd.DataFrame.from_dict(POD_VLIVEM_STRUCTURED, orient="index").reset_index()
df_pod_vlivem.replace("nan", np.nan, inplace=True)
df_pod_vlivem.replace("n/a", np.nan, inplace=True)
df_pod_vlivem["citySize"] = df_pod_vlivem["citySize"].astype("Int64")
df_pod_vlivem["substanceUsed"] = df_pod_vlivem["substanceUsed"].str.replace("amfetamínu","amfetamín").str.replace("metamfetamín","methamphetamine").str.replace("amfetamín","amphetamine")

In [449]:
order = ['index', 'substanceUsed', 'avgAmountUsed', 'avgAmountUsedUnit', 'amountUsed',
       'measuringMethod', 'measuringTime',  'measuringDevice', 'refusedTesting',
       'dateOfOffense', 'timeOfOffense', 'placeOfOffense', 'citySize', 'placeDetails', 'typeOfRoad',
       'vehicleModel', 'vehicleType', 'checkedBy', 
       'reasonForCheck', 'reasonForCheckCategory', 'licenseStatus', 'lawBroken', 'note', 'sentence'
       ]
df_pod_vlivem = df_pod_vlivem[order]

In [450]:
df_pod_vlivem.to_csv("pod_vlivem_attributes_test.csv", index=False)

In [391]:
df_pod_vlivem

,index,substanceUsed,avgAmountUsed,avgAmountUsedUnit,amountUsed,measuringMethod,measuringTime,measuringDevice,refusedTesting,dateOfOffense,...,typeOfRoad,vehicleModel,vehicleType,checkedBy,reasonForCheck,reasonForCheckCategory,licenseStatus,lawBroken,note,sentence
0,95214574,alcohol,0.58,mg/l,0.64 mg/l; 0.55 mg/l; 0.54 mg/l,breath; breath; breath,03:52; 04:24; 04:54,"AlcoQuant 6020 plus, výrobné číslo A409530",False,01.01.2022,...,class_II,VW Golf,car,hliadkou ODI OR PZ Veľký Krtíš,zastavená a kontrolovaná,traffic_check,valid,NaN,Vozidlo malo evidenčné číslo VK 823CM a smer j...,- dňa 01.01.2022 v čase o 03.50 h viedla pod v...
1,95255832,alcohol,0.74,mg/l,0.74 mg/l,breath,NaN,NaN,False,01.01.2022,...,urban,Seat Altea,car,Obvodné oddelenie Policajného zboru Zlaté Moravce,Kontrola vozidla a vodiča,traffic_check,valid,NaN,Vozidlo malo evidenčné číslo LV-XXX EK.,že : po predchádzajúcom požití väčšieho množs...
2,95309650,methamphetamine; amphetamine,NaN,NaN,198.05 ng/ml; 33.56 ng/ml,blood; blood,10:30; 10:30,NaN,False,13.05.2021,...,urban,Dacia Logan,car,policajnou hliadkou,javil známky požitia omamných a psychotropných...,suspected_intoxication,valid,NaN,Podľa znaleckého posudku z odvetvia psychiatri...,", ž e dňa 13. mája 2021 v čase okolo 09.50 ho..."
3,95331065,alcohol,0.26,mg/l,0.26 mg/l,breath,NaN,NaN,False,04.01.2022,...,class_I,anonymized,car,hliadkou ODI Stará Ľubovňa,NaN,traffic_check,banned,NaN,Zákaz činnosti viesť motorové vozidlá na dobu ...,dňa 04.01.2022 v čase okolo 10.11 hod. pod vpl...
4,114902217,cannabis,44.50,ng/ml,7.00 ng/ml; 82.00 ng/ml,blood; blood,23:45; 23:45,NaN,False,19.11.2021,...,class_II,Škoda Octavia,car,OO PZ Čadca,"Kontrolovaný hliadkou OO PZ Čadca, nakoľko jav...",suspected_intoxication,valid,NaN,Vodič sa podrobil dychovej skúške na zistenie ...,dňa 19.11.2021 okolo 21:50 h viedol osobné mot...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1770,101536112,alcohol,0.59,mg/l,0.59 mg/l,breath,03:51,NaN,False,03.04.2022,...,urban,Mitsubishi Carisma,car,policajnou hliadkou,na zistenie požitia alkoholu,suspected_intoxication,valid,§ 4 odsek 2 písmeno d) zákona č. 8/2009 Z.z. o...,Evidenčné číslo vozidla bolo SE-XXXBE a jeho m...,že : dňa 03.04.2022 v čase o 03.51 hod. na ul...
1771,106473883,alcohol,0.61,mg/l,0.54 mg/l; 0.66 mg/l; 0.62 mg/l,breath; breath; breath,16:45; 17:06; 17:25,AlcoQuant 6020 plus,False,11.06.2022,...,NaN,Babeta,motorcycle,Okresný dopravný inšpektorát Trnava,jazda na motocykli bez ochrannej prilby a zo s...,traffic_violation; suspected_intoxication,valid,NaN,Sériové číslo prístroja AlcoQuant 6020 plus bo...,", ž e dňa 11.06.2022 v čase o 16:35 hodine vi..."
1772,108365243,alcohol,0.88,mg/l,0.89 mg/l; 0.82 mg/l; 0.95 mg/l; 0.86 mg/l,breath; breath; breath; breath,21:02; 21:17; 21:36; 22:06,AlcoQuant 6020 plus,False,18.06.2022,...,NaN,Mercedes Benz Vito,van,hliadkou OO PZ Partizánske,predpísaným spôsobom zastavený a kontrolovaný,traffic_check,valid,NaN,Vodič nemal pri sebe doklady potrebné na veden...,: dňa 18.06.2022 v čase o 20:50 h viedol osob...
1773,113761793,alcohol,1.22,mg/l,1.22 mg/l,breath,NaN,NaN,False,19.09.2022,...,urban,anonymized,car,OVS ODI OR PZ Košice,prekročenie povolenej rýchlosti,speeding,valid,NaN,Okrem extrahovaných údajov text uvádza hodnotu...,v Košiciach po ul. Gemerskej k ul. Rastislavov...
1774,106012675,alcohol,0.94,mg/l,0.94 mg/l,breath,19:37,NaN,False,04.06.2022,...,class_II,NaN,other,"Okresné riaditeľstvo PZ, Okresný dopravný inšp...",kontrola,traffic_check,valid,NaN,Páchateľ viedol traktor s evidenčným číslom C.,"dňa 04. 06. 2022 v čase okolo 19.35 hodine, po..."

In [114]:
non_na_series = list(df_pod_vlivem["reasonForCheck"].dropna())

In [125]:
nan_info = df_pod_vlivem.isna().sum().to_frame("NaN count")
nan_info["NaN %"] = (df_pod_vlivem.isna().mean() * 100).round(2)
print(nan_info["NaN %"])

index                 0.00
substanceUsed         4.08
substanceUsedType     8.67
amountUsed           12.76
measuringMethod       8.16
measuringTime        38.27
avgAmountUsed        12.76
measuringDevice      41.84
refusedTesting        0.00
dateOfOffense         0.51
timeOfOffense         0.00
placeOfOffense        1.53
citySize             57.14
placeDetails          0.51
typeOfRoad           17.35
vehicleModel          1.02
vehicleType           0.00
checkedBy            11.73
reasonForCheck       69.39
licenseStatus         0.00
lawBroken            84.18
note                  0.00
sentence              0.00
Name: NaN %, dtype: float64

In [10]:
final = pd.read_csv("pod_vlivem_attributes_1775.csv")

In [404]:
errors = 0
for n,item in enumerate(list(final["measuringMethod"])):
    items = str(item).split(";")
    if any([item.strip() not in ["breath", "blood", "urine", "nan", "na"] for item in items]):
        errors += 1
        print(f"{n}:{item}")

131:breath; breath; breath; blood; other
143:dych; dych
955:n/a; n/a
1225:moč; moč
1350:krv; krv
1537:blood; other; other
1640:blood; other
1762:breath; blood; other

## Validations

In [ ]:
from dateutil.parser import parse

def is_date_after_2000(string):
    try:
        dt = parse(string, fuzzy=False)
        return dt.year > 2000
    except ValueError:
        return False

def check_date_after_2000(row, n, fmt="%H:%M"):
    string = str(row["dateOfOffense"])
    if time == "nan":
        return True
    try:
        dt = parse(string, fuzzy=False)
        if dt.year > 2000:
            return True
        else:
            return False
    except ValueError:
        print(f"dateOfOffense value '{string}' does not match the requirements.")
        return False

errors = 0
for n,item in enumerate(list(final["dateOfOffense"])):
    try:
        if not is_date_after_2000( item):
            errors += 1
            print(f"{n}:{item}")
    except:
        errors+=1

In [ ]:
from datetime import datetime
import math

def is_time(string, fmt="%H:%M"):
    try:
        datetime.strptime(string, fmt)
        return True
    except ValueError:
        return False

def check_time(row, n, fmt="%H:%M"):
    time = str(row["timeOfOffense"])
    if time == "nan":
        return True
    try:
        datetime.strptime(time, fmt)
        return True
    except ValueError:
        print(f"timeOfOffense value '{time}' does not match the requirements.")
        return False

errors = 0
for n,item in enumerate(list(final["timeOfOffense"])):
    try:
        if not is_time( item):
            errors += 1
            print(f"{n}:{item}")
    except:
        errors+=1

In [ ]:
def check_substance(row, n):   

    substances = [
    "alcohol",
    "cannabis",
    "methamphetamine",
    "amphetamine",
    "cocaine",
    "mdma",
    "hashish",
    "morphine",
    "barbiturate",
    "benzodiazepine",
    "methadon",
    "heroin",
    "other",
    "nan"
    ]
    field = row["substanceUsed"]
    items = str(field).split(";")
    if any([item.strip() not in substances for item in items]):
        print(f"{n}:{field}")
        print(f"substanceUsed value '{item}' does not match the requirements.")
        return False
    else:
        #print(f"{n}:{items} is ok")
        return True

errors = 0
for n,row in final.iterrows():
    check_substance(row, n)